

NEw
b2c8c2e65f2f1002065117e701910004

Old: 
22c54f3fbddd10003df7ab68c4f40001

select max(date_and_time_completed) from PO_HRIS_DB."Worker".WORKER_TRANSACTION limit 1


_TYPE where business_process_type like '%Hire%' limit 10;

select * from PO_HRIS_DB."Worker".WORKER_TRANSACTION_TYPE where 
employee_id = //'13fcbd7857d74f9f2507abf04cc5d939ef6daee1317cb9d4335c36b181e2a8f618abfd60452c470d21d3ee026e733428590f40f89436a0957071c27c8480b1b8'

'95cd0b1ec3e57f3fe52169d6d3ad8aa4b5df01be9caaadb231c9f745bede834057c886b32a91ad666a6310e13a7ffaca1630481d8e52cf866d2461ac466598da'


limit 10;

/*Old replaced on 03/05
Create or replace table Worker_Transaction_Stage (
employee_id varchar,
active_status varchar,
age varchar,
aspire_bonus_amount_us varchar,
aspire_bonus_currency varchar,
aspire_target_percent varchar,
base_pay_range_segment varchar,
spe_benefit_code varchar,
spe_occcode_current varchar,
spe_occcode_proposed varchar,
bonus_plan varchar,
business_title_current varchar,
business_title_proposed varchar,
business_uniteffective_dtd varchar,
continuous_service_dt_current varchar,
continuous_service_dt varchar,
cost_center_current varchar,
cost_center_proposed varchar,
cost_element_current_esi varchar,
cost_element_current_ref_id varchar,
cost_element_proposed_esi varchar,
cost_element_proposed_ref_id varchar,
currency_current varchar,
currency_proposed varchar,
base_pay_current varchar,
base_pay_proposed varchar,
department_current varchar,
department_current_id varchar,
department_current_name varchar,
department_proposed varchar,
department_proposed_id varchar,
department_proposed_name varchar,
direct_reports_count varchar,
disability varchar,
division_current varchar,
division_current_id varchar,
division_current_name varchar,
work_city varchar,
division_proposed varchar,
division_proposed_id varchar,
division_proposed_name varchar,
employee_email varchar,
work_country varchar,
work_state varchar,
work_zip varchar,
end_employment_dt varchar,
job_family_current varchar,
job_family_proposed varchar,
job_family_group_current varchar,
job_family_group_proposed varchar,
frequency varchar,
gender varchar,
generation varchar,
hire_dt varchar,
original_hire_dt varchar,
term_dt varchar,
time_in_job varchar,
hispanic_latino varchar,
hourly_rate_current_amount varchar,
hourly_rate_current_amount_currency_code varchar,
hourly_rate_proposed_amount varchar,
hourly_rate_proposed_amount_currency_code varchar,
job_code_current varchar,
job_code_proposed varchar,
job_title_current varchar,
job_title varchar,
last_bonus_dt varchar,
last_increase_amount varchar,
last_increase_amount_dt varchar,
last_increase_percent varchar,
line_of_business varchar,
ltip_amount varchar,
on_leave varchar,
org_level varchar,
payroll_company_current varchar,
payroll_company_current_id varchar,
payroll_company_current_name varchar,
payroll_company_proposed varchar,
payroll_company_proposed_id varchar,
payroll_company_proposed_name varchar,
hr_business_partner varchar,
race_ethnicity varchar,
region_current varchar,
region_proposed varchar,
compensation_plans_current varchar,
compensation_plans_proposed varchar,
compensation_grade_current varchar,
compensation_grade_proposed varchar,
span_of_control varchar,
sub_division_current varchar,
subdivision_current varchar,
sub_division_current_name varchar,
sub_division_proposed varchar,
sub_division_proposed_id varchar,
sub_division_proposed_name varchar,
sub_department_current_name varchar,
sub_department_current_id varchar,
sub_department_proposed_name varchar,
sub_department_proposed_id varchar,
current_manager_name varchar,
current_manager_id varchar,
current_manager_job_title varchar,
manager_current_email varchar,
manager_proposed_name varchar,
manager_proposed_id varchar,
proposed_manager_job_title varchar,
manager_proposed_email varchar,
employee_contingent_worker_type_current varchar,
employee_contingent_worker_type_current_id varchar,
employee_contingent_worker_type_proposed varchar,
employee_contingent_worker_type_proposed_id varchar,
company_current_ref_id varchar,
company_proposed_id varchar,
current_pay_group_ref_id varchar,
current_pay_group_name varchar,
proposed_pay_group varchar,
proposed_pay_group_ref_id varchar,
location_current_ref_id varchar,
location_current_name varchar,
location_proposed_ref_id varchar,
location_proposed_name varchar,
job_profile_current varchar,
job_profile_proposed_ref_id varchar,
job_profile_proposed_name varchar,
vet_status varchar,
change_job_type varchar,
onboard_progress varchar,
initiating_person varchar,
management_level_current varchar,
management_level_current_ref_id varchar,
management_level_proposed varchar,
management_level_proposed_ref_id varchar,
supervisory_org_current varchar,
supervisory_org_current_ref_id varchar,
supervisory_org_proposed varchar,
supervisory_org_proposed_ref_id varchar,
transaction_status varchar,
time_type_current varchar,
time_type_current_ref_id varchar,
time_type_proposed varchar,
time_type_proposed_ref_id varchar,
pay_rate_type_current varchar,
pay_rate_type_current_ref_id varchar,
pay_rate_type_proposed varchar,
pay_rate_type_proposed_ref_id varchar,
paid_fte_current varchar,
paid_fte_proposed varchar,
job_exempt_current varchar,
job_exempt_proposed varchar,
union_name varchar,
union_id varchar,
hourly_rate_current_currency varchar,
hourly_rate_proposed_currency varchar,
last_increase_currency varchar,
ltip_currency varchar,
workday_id varchar,
candidate_id varchar,
action_event varchar,
action_event_instance varchar,
initiated_dt varchar,
date_time_completed varchar,
latest_correction_corrected_dt_and_time varchar,
event_workdayid varchar,
effective_dt varchar,
business_process_type varchar,
business_process_reason_category varchar,
business_process_reason varchar,
initiating_worker_id varchar,
Source_Filename Varchar
);
*/

drop table Worker_Transaction_Stage_Unhashed;

Create or replace table Worker_Transaction_Stage_Unhashed (
employee_id  varchar,
effective_dt  varchar,
date_and_time_completed  varchar,
date_and_time_initiated  varchar,
correction_dt  varchar,
is_activity  varchar,
is_snapshot  varchar,
active_status  varchar,
age  varchar,
aspire_bonus_amount  varchar,
aspire_bonus_plan  varchar,
aspire_bonus_currency  varchar,
aspire_target_percent  varchar,
base_pay_range_segment  varchar,
benefit_code  varchar,
business_partner_employee_id  varchar,
business_partner_name  varchar,
business_partner_current  varchar,
business_partner_proposed  varchar,
business_process_reason_category  varchar,
business_process_reason  varchar,
business_process_type  varchar,
business_title_current  varchar,
business_title_proposed  varchar,
job_title_current  varchar,
job_title_proposed  varchar,
candidate_id  varchar,
base_pay_current  varchar,
base_pay_proposed  varchar,
basis_frequency  varchar,
compensation_grade_current  varchar,
compensation_grade_proposed  varchar,
continuous_service_dt_current  varchar,
continuous_service_dt_proposed  varchar,
currency_current  varchar,
currency_proposed  varchar,
contingent_type_current  varchar,
contingent_type_id_current  varchar,
contingent_type_proposed  varchar,
contingent_type_id_proposed  varchar,
hourly_rate_current  varchar,
hourly_rate_proposed  varchar,
job_profile_current  varchar,
job_profile_id_current  varchar,
job_profile_proposed  varchar,
job_profile_id_proposed  varchar,
default_hours_current  varchar,
default_hours_proposed  varchar,
fte_current  varchar,
fte_proposed  varchar,
d_fte_current  varchar,
d_fte_proposed  varchar,
paid_fte_current  varchar,
paid_fte_proposed  varchar,
generation  varchar,
gl_account_current  varchar,
gl_account_proposed  varchar,
job_level_current  varchar,
job_level_proposed  varchar,
scheduled_hours_current  varchar,
scheduled_hours_proposed  varchar,
pay_rate_type_current  varchar,
pay_rate_type_id_current  varchar,
pay_rate_type_proposed  varchar,
pay_rate_type_id_proposed  varchar,
time_in_job  varchar,
time_type_current  varchar,
time_type_id_current  varchar,
time_type_proposed  varchar,
time_type_id_proposed  varchar,
contract  varchar,
cost_center_grouping_current  varchar,
cost_center_grouping_name_current  varchar,
cost_center_grouping_id_current  varchar,
cost_center_grouping_proposed  varchar,
cost_center_grouping_name_proposed  varchar,
cost_center_grouping_id_proposed  varchar,
cost_element_id_current  varchar,
cost_element_name_current  varchar,
cost_element_id_proposed  varchar,
cost_element_name_proposed  varchar,
department_current  varchar,
department_id_current  varchar,
department_name_current  varchar,
department_proposed  varchar,
department_id_proposed  varchar,
department_name_proposed  varchar,
disability  varchar,
division_current  varchar,
division_id_current  varchar,
division_name_current  varchar,
division_proposed  varchar,
division_id_proposed  varchar,
division_name_proposed  varchar,
employee_class  varchar,
work_email  varchar,
end_employment_dt  varchar,
event_wid  varchar,
flsa_status  varchar,
gender  varchar,
geographic_group_current  varchar,
geographic_group_proposed  varchar,
hire_dt  varchar,
original_hire_dt  varchar,
hispanic_or_latino  varchar,
initiating_person  varchar,
initiating_person_id  varchar,
job_code_current  varchar,
job_code_proposed  varchar,
job_family_current  varchar,
job_family_proposed  varchar,
job_family_group_current  varchar,
job_family_group_proposed  varchar,
ltip_bonus_amount  varchar,
ltip_currency  varchar,
last_bonus_dt  varchar,
last_increase_amount  varchar,
last_increase_currency  varchar,
last_increase_percent  varchar,
last_increase_dt  varchar,
legacy_compensation_plans_current  varchar,
legacy_compensation_plans_proposed  varchar,
new_compensation_plans_current  varchar,
new_compensation_plans_proposed  varchar,
line_of_business_current  varchar,
line_of_business_id_current  varchar,
line_of_business_name_current  varchar,
line_of_business_proposed  varchar,
line_of_business_id_proposed  varchar,
line_of_business_name_proposed  varchar,
location_id_current  varchar,
location_name_current  varchar,
location_id_proposed  varchar,
location_name_proposed  varchar,
work_address_city  varchar,
work_address_state  varchar,
work_address_country  varchar,
work_address_postal_code  varchar,
job_exempt_current  varchar,
job_exempt_proposed  varchar,
management_level_current  varchar,
management_level_id_current  varchar,
management_level_proposed  varchar,
management_level_id_proposed  varchar,
supervisory_organization_current  varchar,
supervisory_organization_id_current  varchar,
supervisory_organization_proposed  varchar,
supervisory_organization_id_proposed  varchar,
manager_id_current  varchar,
manager_name_current  varchar,
manager_id_proposed  varchar,
manager_name_proposed  varchar,
manager_job_title_current  varchar,
manager_job_title_proposed  varchar,
manager_work_email_current  varchar,
manager_work_email_proposed  varchar,
direct_report_count  varchar,
span_of_control  varchar,
occ_code_current  varchar,
occ_code_proposed  varchar,
on_leave  varchar,
organization_level_code  varchar,
other_id_legacy_current  varchar,
other_id_legacy_proposed  varchar,
other_id_new_current  varchar,
other_id_new_proposed  varchar,
pay_company_current  varchar,
pay_company_id_current  varchar,
pay_company_name_current  varchar,
pay_company_proposed  varchar,
pay_company_id_proposed  varchar,
pay_company_name_proposed  varchar,
pay_group_id_current  varchar,
pay_group_name_current  varchar,
pay_group_id_proposed  varchar,
pay_group_name_proposed  varchar,
pay_plan  varchar,
planning_manager_current  varchar,
planning_manager_id_current  varchar,
planning_manager_name_current  varchar,
planning_manager_proposed  varchar,
planning_manager_id_proposed  varchar,
planning_manager_name_proposed  varchar,
pre_hire_id  varchar,
pre_hire_wid  varchar,
profit_center_current  varchar,
profit_center_id_current  varchar,
profit_center_name_current  varchar,
profit_center_proposed  varchar,
profit_center_id_proposed  varchar,
profit_center_name_proposed  varchar,
race_ethnicity  varchar,
region_current  varchar,
region_proposed  varchar,
regular_temp  varchar,
sap_company_current  varchar,
sap_company_id_current  varchar,
sap_company_name_current  varchar,
sap_company_proposed  varchar,
sap_company_id_proposed  varchar,
sap_company_name_proposed  varchar,
sony_payroll_company_current  varchar,
sony_payroll_company_id_current  varchar,
sony_payroll_company_name_current  varchar,
sony_payroll_company_proposed  varchar,
sony_payroll_company_id_proposed  varchar,
sony_payroll_company_name_proposed  varchar,
source  varchar,
union_local_name  varchar,
union_code  varchar,
sub_department_current  varchar,
sub_department_id_current  varchar,
sub_department_name_current  varchar,
sub_department_proposed  varchar,
sub_department_id_proposed  varchar,
sub_department_name_proposed  varchar,
sub_division_current  varchar,
sub_division_id_current  varchar,
sub_division_name_current  varchar,
sub_division_proposed  varchar,
sub_division_id_proposed  varchar,
sub_division_name_proposed  varchar,
termination_dt  varchar,
transaction_status  varchar,
trended_record_dt  varchar,
veteran_status  varchar,
worker_wid  varchar,
Source_Filename Varchar
);

Create or replace table Worker_Transaction_Type (
Employee_ID Varchar(130),
Effective_Dt Date,
Business_Process_Reason_Category Varchar(30),
Business_Process_Reason Varchar(60),
Business_Process_Type Varchar(50),
Source Varchar(50),
Created_Date timestamp_ntz,
Created_By Varchar(100),
Modified_Date timestamp_ntz,
Modifeid_By Varchar(100),
Batch_ID Integer
)
;


Create or replace table Worker_Transaction (
Employee_ID Varchar(130),
Effective_Dt Date,
Date_and_Time_Completed Date,
Date_and_Time_Initiated Date,
Correction_Dt Date,
Is_Activity boolean,
Is_Snapshot boolean,
Active_Status Varchar(10),
Age Varchar(10),
ASPIRE_Bonus_Amount Varchar(20),
ASPIRE_Bonus_Plan Varchar(140),
ASPIRE_Bonus_Currency Varchar(10),
ASPIRE_Target_Percent Varchar(10),
Base_Pay_Range_Segment Varchar(20),
Benefit_Code Varchar(10),
Business_Partner_Employee_ID Varchar(130),
Business_Partner_Name Varchar(130),
Business_Partner_Current Varchar(130),
Business_Partner_Proposed Varchar(130),
Business_Title_Current Varchar(130),
Business_Title_Proposed Varchar(120),
Job_Title_Current Varchar(120),
Job_Title_Proposed Varchar(120),
Candidate_ID Varchar(130),
Base_Pay_Current Varchar(20),
Base_Pay_Proposed Varchar(20),
Basis_Frequency Varchar(30),
Compensation_Grade_Current Varchar(30),
Compensation_Grade_Proposed Varchar(30),
Continuous_Service_Dt_Current Date,
Continuous_Service_Dt_Proposed Date,
Currency_Current Varchar(10),
Currency_Proposed Varchar(10),
Contingent_Type_Current Varchar(50),
Contingent_Type_Proposed Varchar(50),
Contingent_Type_ID_Current Varchar(30),
Contingent_Type_ID_Proposed Varchar(30),
Hourly_Rate_Current Varchar(10),
Hourly_Rate_Proposed Varchar(10),
Job_Profile_Current Varchar(90),
Job_Profile_Proposed Varchar(90),
Job_Profile_ID_Current Varchar(30),
Job_Profile_ID_Proposed Varchar(30),
Default_Hours_Current Varchar(10),
Default_Hours_Proposed Varchar(10),
FTE_Current Varchar(10),
FTE_Proposed Varchar(10),
Paid_FTE_Current Varchar(10),
Paid_FTE_Proposed Varchar(10),
Generation Varchar(40),
GL_Account_Current Varchar(10),
GL_Account_Proposed Varchar(10),
Job_Level_Current Varchar(20),
Job_Level_Proposed Varchar(20),
Scheduled_Hours_Current Varchar(10),
Scheduled_Hours_Proposed Varchar(10),
Pay_Rate_Type_Current Varchar(20),
Pay_Rate_Type_Proposed Varchar(20),
Pay_Rate_Type_ID_Current Varchar(20),
Pay_Rate_Type_ID_Proposed Varchar(20),
Time_in_Job Varchar(40),
Time_Type_Current Varchar(10),
Time_Type_Proposed Varchar(10),
Time_Type_ID_Current Varchar(10),
Time_Type_ID_Proposed Varchar(10),
Contract Varchar(10),
Cost_Center_Grouping_Current Varchar(70),
Cost_Center_Grouping_Proposed Varchar(70),
Cost_Center_Grouping_Name_Current Varchar(50),
Cost_Center_Grouping_Name_Proposed Varchar(10),
Cost_Center_Grouping_ID_Current Varchar(10),
Cost_Center_Grouping_ID_Proposed Varchar(10),
Cost_Element_Name_Current Varchar(50),
Cost_Element_Name_Proposed Varchar(50),
Cost_Element_ID_Current Varchar(20),
Cost_Element_ID_Proposed Varchar(20),
Department_Current Varchar(90),
Department_Proposed Varchar(90),
Department_ID_Current Varchar(10),
Department_ID_Proposed Varchar(10),
Department_Name_Current Varchar(80),
Department_Name_Proposed Varchar(80),
Disability Varchar(60),
Division_Current Varchar(60),
Division_Proposed Varchar(60),
Division_ID_Current Varchar(10),
Division_ID_Proposed Varchar(10),
Division_Name_Current Varchar(50),
Division_Name_Proposed Varchar(50),
Employee_Class Varchar(10),
Work_Email Varchar(130),
End_Employment_Dt date,
Event_WID Varchar(40),
FLSA_Status Varchar(10),
Gender Varchar(30),
Geographic_Group_Current Varchar(30),
Geographic_Group_Proposed Varchar(30),
Hire_Dt date,
Original_Hire_Dt date,
Hispanic_or_Latino Varchar(10),
Initiating_Person Varchar(60),
Initiating_Person_ID Varchar(40),
Job_Code_Current Varchar(30),
Job_Code_Proposed Varchar(30),
Job_Family_Current Varchar(60),
Job_Family_Proposed Varchar(60),
Job_Family_Group_Current Varchar(50),
Job_Family_Group_Proposed Varchar(50),
LTIP_Bonus_Amount Varchar(10),
LTIP_Currency Varchar(10),
Last_Bonus_Dt Date,
Last_Increase_Amount Varchar(20),
Last_Increase_Currency Varchar(10),
Last_Increase_Percent Varchar(10),
Last_Increase_Dt Date,
Legacy_Compensation_Plans_Current Varchar(420),
Legacy_Compensation_Plans_Proposed Varchar(420),
New_Compensation_Plans_Current Varchar(100),
New_Compensation_Plans_Proposed Varchar(100),
Line_of_Business_Current Varchar(40),
Line_of_Business_Proposed Varchar(40),
Line_of_Business_ID_Current Varchar(30),
Line_of_Business_ID_Proposed Varchar(30),
Line_of_Business_Name_Current Varchar(30),
Line_of_Business_Name_Proposed Varchar(30),
Location_ID_Current Varchar(20),
Location_ID_Proposed Varchar(20),
Location_Name_Current Varchar(80),
Location_Name_Proposed Varchar(80),
Work_Address_City Varchar(30),
Work_Address_State Varchar(40),
Work_Address_Country Varchar(30),
Work_Address_Postal_Code Varchar(20),
Job_Exempt_Current Varchar(10),
Job_Exempt_Proposed Varchar(10),
Management_Level_Current Varchar(30),
Management_Level_Proposed Varchar(30),
Management_Level_ID_Current Varchar(10),
Management_Level_ID_Proposed Varchar(10),
Supervisory_Organization_Current Varchar(130),
Supervisory_Organization_Proposed Varchar(130),
Supervisory_Organization_ID_Current Varchar(40),
Supervisory_Organization_ID_Proposed Varchar(40),
Manager_ID_Current Varchar(130),
Manager_ID_Proposed Varchar(130),
Manager_Name_Current Varchar(130),
Manager_Name_Proposed Varchar(130),
Manager_Job_Title_Current Varchar(120),
Manager_Job_Title_Proposed Varchar(120),
Manager_Work_Email_Current Varchar(130),
Manager_Work_Email_Proposed Varchar(130),
Direct_Report_Count Varchar(10),
Span_of_Control Varchar(10),
Occ_Code_Current Varchar(20),
Occ_Code_Proposed Varchar(20),
On_Leave Varchar(10),
Organization_Level_Code Varchar(20),
Other_ID_Legacy_Current Varchar(1080),
Other_ID_Legacy_Proposed Varchar(1080),
Other_ID_New_Current Varchar(50),
Other_ID_New_Proposed Varchar(50),
Pay_Company_Current Varchar(50),
Pay_Company_Proposed Varchar(50),
Pay_Company_ID_Current Varchar(10),
Pay_Company_ID_Proposed Varchar(10),
Pay_Company_Name_Current Varchar(50),
Pay_Company_Name_Proposed Varchar(50),
Pay_Group_ID_Current Varchar(30),
Pay_Group_ID_Proposed Varchar(30),
Pay_Group_Name_Current Varchar(30),
Pay_Group_Name_Proposed Varchar(30),
Pay_Plan Varchar(10),
Planning_Manager_Current Varchar(40),
Planning_Manager_Proposed Varchar(40),
Planning_Manager_ID_Current Varchar(10),
Planning_Manager_ID_Proposed Varchar(10),
Planning_Manager_Name_Current Varchar(40),
Planning_Manager_Name_Proposed Varchar(40),
Pre_Hire_ID Varchar(20),
Pre_Hire_WID Varchar(40),
Profit_Center_Current Varchar(60),
Profit_Center_Proposed Varchar(60),
Profit_Center_ID_Current Varchar(20),
Profit_Center_ID_Proposed Varchar(20),
Profit_Center_Name_Current Varchar(50),
Profit_Center_Name_Proposed Varchar(50),
Race_Ethnicity Varchar(100),
Region_Current Varchar(20),
Region_Proposed Varchar(20),
Regular_Temp Varchar(10),
SAP_Company_Current Varchar(70),
SAP_Company_Proposed Varchar(70),
SAP_Company_ID_Current Varchar(10),
SAP_Company_ID_Proposed Varchar(10),
SAP_Company_Name_Current Varchar(50),
SAP_Company_Name_Proposed Varchar(50),
Sony_Payroll_Company_Current Varchar(50),
Sony_Payroll_Company_Proposed Varchar(50),
Sony_Payroll_Company_ID_Current Varchar(30),
Sony_Payroll_Company_ID_Proposed Varchar(30),
Sony_Payroll_Company_Name_Current Varchar(40),
Sony_Payroll_Company_Name_Proposed Varchar(40),
Source Varchar(20),
Union_Local_Name Varchar(80),
Union_Code Varchar(70),
Sub_Department_Current Varchar(90),
Sub_Department_ID_Current Varchar(10),
Sub_Department_Name_Current Varchar(80),
Sub_Department_Proposed Varchar(90),
Sub_Department_ID_Proposed Varchar(10),
Sub_Department_Name_Proposed Varchar(80),
Sub_Division_Current Varchar(70),
Sub_Division_ID_Current Varchar(10),
Sub_Division_Name_Current Varchar(60),
Sub_Division_Proposed Varchar(70),
Sub_Division_ID_Proposed Varchar(10),
Sub_Division_Name_Proposed Varchar(60),
Termination_Dt Date,
Trended_Record_Dt Varchar(10),
Veteran_Status Varchar(70),
Worker_WID Varchar(40),
Source_Filename Varchar(500),
Created_Date timestamp_ntz,
Created_By Varchar(100),
Modified_Date timestamp_ntz,
Modifeid_By Varchar(100),
Batch_ID Integer
)
CLUSTER BY (Employee_ID,Effective_Dt,Source);


truncate table "PO_STAGE_DB"."Worker".Worker_Transaction_Stage;

copy into "PO_STAGE_DB"."Worker".Worker_Transaction_Stage
from (select 
$1,
$2,
$3,
$4,
$5,
$6,
$7,
$8,
$9,
$10,
$11,
$12,
$13,
$14,
$15,
$16,
$17,
$18,
$19,
$20,
$21,
$22,
$23,
$24,
$25,
$26,
$27,
$28,
$29,
$30,
$31,
$32,
$33,
$34,
$35,
$36,
$37,
$38,
$39,
$40,
$41,
$42,
$43,
$44,
$45,
$46,
$47,
$48,
$49,
$50,
$51,
$52,
$53,
$54,
$55,
$56,
$57,
$58,
$59,
$60,
$61,
$62,
$63,
$64,
$65,
$66,
$67,
$68,
$69,
$70,
$71,
$72,
$73,
$74,
$75,
$76,
$77,
$78,
$79,
$80,
$81,
$82,
$83,
$84,
$85,
$86,
$87,
$88,
$89,
$90,
$91,
$92,
$93,
$94,
$95,
$96,
$97,
$98,
$99,
$100,
$101,
$102,
$103,
$104,
$105,
$106,
$107,
$108,
$109,
$110,
$111,
$112,
$113,
$114,
$115,
$116,
$117,
$118,
$119,
$120,
$121,
$122,
$123,
$124,
$125,
$126,
$127,
$128,
$129,
$130,
$131,
$132,
$133,
$134,
$135,
$136,
$137,
$138,
$139,
$140,
$141,
$142,
$143,
$144,
$145,
$146,
$147,
$148,
$149,
$150,
$151,
$152,
$153,
$154,
$155,
$156,
$157,
$158,
$159,
$160,
$161,
$162,
$163,
$164,
$165,
$166,
$167,
$168,
$169,
$170,
$171,
$172,
$173,
$174,
$175,
$176,
$177,
$178,
$179,
$180,
$181,
$182,
$183,
$184,
$185,
$186,
$187,
$188,
$189,
$190,
$191,
$192,
$193,
$194,
$195,
$196,
$197,
$198,
$199,
$200,
$201,
$202,
$203,
$204,
$205,
$206,
$207,
$208,
$209,
$210,
$211,
$212,
$213,
$214,
$215,
$216,
$217,
$218,
$219,
$220,
$221,
$222,
$223,
$224,
$225,
$226,
$227,
METADATA$FILENAME
from @PO_STAGE_DB.PUBLIC.MY_S3_STAGE) 
pattern = '.*WD_Business_Process_Trans_2024.*20240624.*csv'
FILE_FORMAT = (  FORMAT_NAME = 'PO_STAGE_DB."Worker".csv_load_format'  TYPE = CSV ) 
;

new_compensation_plans_current ,
new_compensation_plans_proposed ,
other_id_new_current ,
other_id_new_proposed ,

ALTER TABLE PO_HRIS_DB."Worker".WORKER_TRANSACTION ALTER other_id_new_proposed SET DATA TYPE VARCHAR;

/* Testing Final */ 03122024

select *
from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage where effective_dt between '2024-01-01' and '2024-03-31'

select count(distinct employee_id)
from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage_unhashed where effective_dt between '2024-01-01' and '2024-03-31' limit 10

worker_wid = 'b2c8c2e65f2f100205d4c1b2412c0000';


select business_partner,* from PO_HRIS_DB."Worker".PO_WORKER_SNAPSHOT where snapshot_dt = '2023-10-31' //and workday_id = 'b2c8c2e65f2f100205c0c71af1040006'
and employee_id = '88fbca56bd9cf3ce788e74acf50833df5b4a5aa17da0e62a6dffbaa6d33c67a30c5929afb5a7746d6c87f8103ae0518e24319d3db4c4e747d1e8a0674a83aae3' limit 10;

20a9b498a20d17755d3963c858100ba4bd8877461c3aebfcdf33b74ed4cdecb66920f5e5a715791fe9d61ccc562b54ea69e27697ee7e460f0f47a088c4b24bcc

select * from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage where worker_wid = 'b2c8c2e65f2f100205c0c71af1040006';



select count(distinct candidate_id)
from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage where  correction_dt is not null limit 10;

select count(*),event_wid
from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage where event_wid is not null group by 2 having count(*) > 1;

select  distinct source
from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage where effective_dt::date between '2024-01-01' and '2024-01-13'  and BUSINESS_PROCESS_TYPE like '%Hire%';


limit 10;
where business_process_type = 'Hire' and effective_dt >='2024-02-27';





business_process_type = 'Assign Pay Group' and effective_dt::date > '2023-01-01'
limit 10;

select distinct business_process_type,business_process_reason_category ,business_process_reason from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage order by 1,2,3;

select count(*)
from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage limit 10;--902495

select distinct
employee_id ,
effective_dt ,
//date_and_time_completed ,
//date_and_time_initiated ,
correction_dt ,
//is_activity ,
//is_snapshot ,
active_status ,
age ,
aspire_bonus_amount ,
aspire_bonus_plan ,
aspire_bonus_currency ,
aspire_target_percent ,
base_pay_range_segment ,
benefit_code ,
business_partner_employee_id ,
business_partner_name ,
business_partner_current ,
business_partner_proposed ,
//business_process_reason_category ,
//business_process_reason ,
//business_process_type ,
business_title_current ,
business_title_proposed ,
job_title_current ,
job_title_proposed ,
candidate_id ,
base_pay_current ,
base_pay_proposed ,
basis_frequency ,
compensation_grade_current ,
compensation_grade_proposed ,
continuous_service_dt_current ,
continuous_service_dt_proposed ,
currency_current ,
currency_proposed ,
contingent_type_current ,
contingent_type_id_current ,
contingent_type_proposed ,
contingent_type_id_proposed ,
hourly_rate_current ,
hourly_rate_proposed ,
job_profile_current ,
job_profile_id_current ,
job_profile_proposed ,
job_profile_id_proposed ,
default_hours_current ,
default_hours_proposed ,
fte_current ,
fte_proposed ,
d_fte_current ,
d_fte_proposed ,
paid_fte_current ,
paid_fte_proposed ,
generation ,
gl_account_current ,
gl_account_proposed ,
job_level_current ,
job_level_proposed ,
scheduled_hours_current ,
scheduled_hours_proposed ,
pay_rate_type_current ,
pay_rate_type_id_current ,
pay_rate_type_proposed ,
pay_rate_type_id_proposed ,
time_in_job ,
time_type_current ,
time_type_id_current ,
time_type_proposed ,
time_type_id_proposed ,
contract ,
cost_center_grouping_current ,
cost_center_grouping_name_current ,
cost_center_grouping_id_current ,
cost_center_grouping_proposed ,
cost_center_grouping_name_proposed ,
cost_center_grouping_id_proposed ,
cost_element_id_current ,
cost_element_name_current ,
cost_element_id_proposed ,
cost_element_name_proposed ,
department_current ,
department_id_current ,
department_name_current ,
department_proposed ,
department_id_proposed ,
department_name_proposed ,
disability ,
division_current ,
division_id_current ,
division_name_current ,
division_proposed ,
division_id_proposed ,
division_name_proposed ,
employee_class ,
work_email ,
end_employment_dt ,
//event_wid ,
flsa_status ,
gender ,
geographic_group_current ,
geographic_group_proposed ,
hire_dt ,
original_hire_dt ,
hispanic_or_latino ,
//initiating_person ,
//initiating_person_id ,
job_code_current ,
job_code_proposed ,
job_family_current ,
job_family_proposed ,
job_family_group_current ,
job_family_group_proposed ,
ltip_bonus_amount ,
ltip_currency ,
last_bonus_dt ,
last_increase_amount ,
last_increase_currency ,
last_increase_percent ,
last_increase_dt ,
legacy_compensation_plans_current ,
legacy_compensation_plans_proposed ,
new_compensation_plans_current ,
new_compensation_plans_proposed ,
line_of_business_current ,
line_of_business_id_current ,
line_of_business_name_current ,
line_of_business_proposed ,
line_of_business_id_proposed ,
line_of_business_name_proposed ,
location_id_current ,
location_name_current ,
location_id_proposed ,
location_name_proposed ,
work_address_city ,
work_address_state ,
work_address_country ,
work_address_postal_code ,
job_exempt_current ,
job_exempt_proposed ,
management_level_current ,
management_level_id_current ,
management_level_proposed ,
management_level_id_proposed ,
supervisory_organization_current ,
supervisory_organization_id_current ,
supervisory_organization_proposed ,
supervisory_organization_id_proposed ,
manager_id_current ,
manager_name_current ,
manager_id_proposed ,
manager_name_proposed ,
manager_job_title_current ,
manager_job_title_proposed ,
manager_work_email_current ,
manager_work_email_proposed ,
direct_report_count ,
span_of_control ,
occ_code_current ,
occ_code_proposed ,
on_leave ,
organization_level_code ,
other_id_legacy_current ,
other_id_legacy_proposed ,
other_id_new_current ,
other_id_new_proposed ,
pay_company_current ,
pay_company_id_current ,
pay_company_name_current ,
pay_company_proposed ,
pay_company_id_proposed ,
pay_company_name_proposed ,
pay_group_id_current ,
pay_group_name_current ,
pay_group_id_proposed ,
pay_group_name_proposed ,
pay_plan ,
planning_manager_current ,
planning_manager_id_current ,
planning_manager_name_current ,
planning_manager_proposed ,
planning_manager_id_proposed ,
planning_manager_name_proposed ,
pre_hire_id ,
pre_hire_wid ,
profit_center_current ,
profit_center_id_current ,
profit_center_name_current ,
profit_center_proposed ,
profit_center_id_proposed ,
profit_center_name_proposed ,
race_ethnicity ,
region_current ,
region_proposed ,
regular_temp ,
sap_company_current ,
sap_company_id_current ,
sap_company_name_current ,
sap_company_proposed ,
sap_company_id_proposed ,
sap_company_name_proposed ,
sony_payroll_company_current ,
sony_payroll_company_id_current ,
sony_payroll_company_name_current ,
sony_payroll_company_proposed ,
sony_payroll_company_id_proposed ,
sony_payroll_company_name_proposed ,
//source ,
union_local_name ,
union_code ,
sub_department_current ,
sub_department_id_current ,
sub_department_name_current ,
sub_department_proposed ,
sub_department_id_proposed ,
sub_department_name_proposed ,
sub_division_current ,
sub_division_id_current ,
sub_division_name_current ,
sub_division_proposed ,
sub_division_id_proposed ,
sub_division_name_proposed ,
termination_dt ,
transaction_status ,
//trended_record_dt ,
veteran_status ,
worker_wid 
;select *
from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage 
WHERE employee_id = 'e7680a352a479f41aec19496302ba98112cdf8bec289a37f9cc36ce7a8a4423b05fc98e80a80cbf25ab18c7fc8a31424003cb96688c7b19c4d4e1d43a9446d01'
and effective_dt = '2020-06-29';

select employee_id,business_process_reason_category ,
business_process_reason ,
business_process_type ,source,effective_dt ,hire_dt,
date_and_time_completed ,
date_and_time_initiated ,
correction_dt ,
BASE_PAY_CURRENT,BASE_PAY_PROPOSED,BASIS_FREQUENCY,HOURLY_RATE_CURRENT,HOURLY_RATE_PROPOSED,LAST_INCREASE_AMOUNT,LAST_INCREASE_AMOUNT,LAST_INCREASE_DT
is_activity ,
is_snapshot ,
active_status ,worker_wid,event_wid,candidate_id,PRE_HIRE_ID,PRE_HIRE_WID
from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage 
where //source = 'New Activity' and BUSINESS_PROCESS_TYPE = 'Request Compensation Change'; //and event_wid is not null - no records
employee_id = 'e7680a352a479f41aec19496302ba98112cdf8bec289a37f9cc36ce7a8a4423b05fc98e80a80cbf25ab18c7fc8a31424003cb96688c7b19c4d4e1d43a9446d01'--req comp change example
and effective_dt = '2020-06-29';


select * from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage where business_process_reason = 'Promotion'
select distinct
row_number() over(partition by employee_id,effective_dt::date,source order by date_and_time_completed::date ),
employee_id ,
effective_dt ,
date_and_time_initiated ,
date_and_time_completed ,
is_activity ,
is_snapshot ,
business_process_reason_category ,
business_process_reason ,
business_process_type ,
event_wid ,
pre_hire_id ,
pre_hire_wid ,
candidate_id,
source,
trended_record_dt,
active_status ,
age ,
aspire_bonus_amount ,
aspire_bonus_plan ,
aspire_bonus_currency ,
aspire_target_percent ,
base_pay_range_segment ,
benefit_code ,
business_partner_employee_id ,
business_partner_name ,
business_partner_current ,
business_partner_proposed ,
business_title_current ,
business_title_proposed ,
job_title_current ,
job_title_proposed ,
base_pay_current ,
base_pay_proposed ,
basis_frequency ,
compensation_grade_current ,
compensation_grade_proposed ,
continuous_service_dt_current ,
continuous_service_dt_proposed ,
currency_current ,
currency_proposed ,
contingent_type_current ,
contingent_type_id_current ,
contingent_type_proposed ,
contingent_type_id_proposed ,
hourly_rate_current ,
hourly_rate_proposed ,
job_profile_current ,
job_profile_id_current ,
job_profile_proposed ,
job_profile_id_proposed ,
default_hours_current ,
default_hours_proposed ,
fte_current ,
fte_proposed ,
d_fte_current ,
d_fte_proposed ,
paid_fte_current ,
paid_fte_proposed ,
generation ,
gl_account_current ,
gl_account_proposed ,
job_level_current ,
job_level_proposed ,
scheduled_hours_current ,
scheduled_hours_proposed ,
pay_rate_type_current ,
pay_rate_type_id_current ,
pay_rate_type_proposed ,
pay_rate_type_id_proposed ,
time_in_job ,
time_type_current ,
time_type_id_current ,
time_type_proposed ,
time_type_id_proposed ,
contract ,
cost_center_grouping_current ,
cost_center_grouping_name_current ,
cost_center_grouping_id_current ,
cost_center_grouping_proposed ,
cost_center_grouping_name_proposed ,
cost_center_grouping_id_proposed ,
cost_element_id_current ,
cost_element_name_current ,
cost_element_id_proposed ,
cost_element_name_proposed ,
department_current ,
department_id_current ,
department_name_current ,
department_proposed ,
department_id_proposed ,
department_name_proposed ,
disability ,
division_current ,
division_id_current ,
division_name_current ,
division_proposed ,
division_id_proposed ,
division_name_proposed ,
employee_class ,
work_email ,
end_employment_dt ,

flsa_status ,
gender ,
geographic_group_current ,
geographic_group_proposed ,
hire_dt ,
original_hire_dt ,
hispanic_or_latino ,

job_code_current ,
job_code_proposed ,
job_family_current ,
job_family_proposed ,
job_family_group_current ,
job_family_group_proposed ,
ltip_bonus_amount ,
ltip_currency ,
last_bonus_dt ,
last_increase_amount ,
last_increase_currency ,
last_increase_percent ,
last_increase_dt ,
legacy_compensation_plans_current ,
legacy_compensation_plans_proposed ,
new_compensation_plans_current ,
new_compensation_plans_proposed ,
line_of_business_current ,
line_of_business_id_current ,
line_of_business_name_current ,
line_of_business_proposed ,
line_of_business_id_proposed ,
line_of_business_name_proposed ,
location_id_current ,
location_name_current ,
location_id_proposed ,
location_name_proposed ,
work_address_city ,
work_address_state ,
work_address_country ,
work_address_postal_code ,
job_exempt_current ,
job_exempt_proposed ,
management_level_current ,
management_level_id_current ,
management_level_proposed ,
management_level_id_proposed ,
supervisory_organization_current ,
supervisory_organization_id_current ,
supervisory_organization_proposed ,
supervisory_organization_id_proposed ,
manager_id_current ,
manager_name_current ,
manager_id_proposed ,
manager_name_proposed ,
manager_job_title_current ,
manager_job_title_proposed ,
manager_work_email_current ,
manager_work_email_proposed ,
direct_report_count ,
span_of_control ,
occ_code_current ,
occ_code_proposed ,
on_leave ,
organization_level_code ,
other_id_legacy_current ,
other_id_legacy_proposed ,
other_id_new_current ,
other_id_new_proposed ,
pay_company_current ,
pay_company_id_current ,
pay_company_name_current ,
pay_company_proposed ,
pay_company_id_proposed ,
pay_company_name_proposed ,
pay_group_id_current ,
pay_group_name_current ,
pay_group_id_proposed ,
pay_group_name_proposed ,
pay_plan ,
planning_manager_current ,
planning_manager_id_current ,
planning_manager_name_current ,
planning_manager_proposed ,
planning_manager_id_proposed ,
planning_manager_name_proposed ,
pre_hire_id ,
pre_hire_wid ,
profit_center_current ,
profit_center_id_current ,
profit_center_name_current ,
profit_center_proposed ,
profit_center_id_proposed ,
profit_center_name_proposed ,
race_ethnicity ,
region_current ,
region_proposed ,
regular_temp ,
sap_company_current ,
sap_company_id_current ,
sap_company_name_current ,
sap_company_proposed ,
sap_company_id_proposed ,
sap_company_name_proposed ,
sony_payroll_company_current ,
sony_payroll_company_id_current ,
sony_payroll_company_name_current ,
sony_payroll_company_proposed ,
sony_payroll_company_id_proposed ,
sony_payroll_company_name_proposed ,
union_local_name ,
union_code ,
sub_department_current ,
sub_department_id_current ,
sub_department_name_current ,
sub_department_proposed ,
sub_department_id_proposed ,
sub_department_name_proposed ,
sub_division_current ,
sub_division_id_current ,
sub_division_name_current ,
sub_division_proposed ,
sub_division_id_proposed ,
sub_division_name_proposed ,
termination_dt ,
veteran_status 
 from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage
 where employee_id = 'e7680a352a479f41aec19496302ba98112cdf8bec289a37f9cc36ce7a8a4423b05fc98e80a80cbf25ab18c7fc8a31424003cb96688c7b19c4d4e1d43a9446d01'; order by effective_dt ,date_and_time_completed ;
 
 
select //count(*),event_wid
count(*),employee_id,effective_dt --402393
from 

(
select distinct
employee_id ,
effective_dt ,
//date_and_time_completed ,
//date_and_time_initiated ,
correction_dt ,
//is_activity ,
//is_snapshot ,
active_status ,
age ,
aspire_bonus_amount ,
aspire_bonus_plan ,
aspire_bonus_currency ,
aspire_target_percent ,
base_pay_range_segment ,
benefit_code ,
business_partner_employee_id ,
business_partner_name ,
business_partner_current ,
business_partner_proposed ,
//business_process_reason_category ,
//business_process_reason ,
//business_process_type ,
business_title_current ,
business_title_proposed ,
job_title_current ,
job_title_proposed ,
candidate_id ,
base_pay_current ,
base_pay_proposed ,
basis_frequency ,
compensation_grade_current ,
compensation_grade_proposed ,
continuous_service_dt_current ,
continuous_service_dt_proposed ,
currency_current ,
currency_proposed ,
contingent_type_current ,
contingent_type_id_current ,
contingent_type_proposed ,
contingent_type_id_proposed ,
hourly_rate_current ,
hourly_rate_proposed ,
job_profile_current ,
job_profile_id_current ,
job_profile_proposed ,
job_profile_id_proposed ,
default_hours_current ,
default_hours_proposed ,
fte_current ,
fte_proposed ,
d_fte_current ,
d_fte_proposed ,
paid_fte_current ,
paid_fte_proposed ,
generation ,
gl_account_current ,
gl_account_proposed ,
job_level_current ,
job_level_proposed ,
scheduled_hours_current ,
scheduled_hours_proposed ,
pay_rate_type_current ,
pay_rate_type_id_current ,
pay_rate_type_proposed ,
pay_rate_type_id_proposed ,
time_in_job ,
time_type_current ,
time_type_id_current ,
time_type_proposed ,
time_type_id_proposed ,
contract ,
cost_center_grouping_current ,
cost_center_grouping_name_current ,
cost_center_grouping_id_current ,
cost_center_grouping_proposed ,
cost_center_grouping_name_proposed ,
cost_center_grouping_id_proposed ,
cost_element_id_current ,
cost_element_name_current ,
cost_element_id_proposed ,
cost_element_name_proposed ,
department_current ,
department_id_current ,
department_name_current ,
department_proposed ,
department_id_proposed ,
department_name_proposed ,
disability ,
division_current ,
division_id_current ,
division_name_current ,
division_proposed ,
division_id_proposed ,
division_name_proposed ,
employee_class ,
work_email ,
end_employment_dt ,
//event_wid ,
flsa_status ,
gender ,
geographic_group_current ,
geographic_group_proposed ,
hire_dt ,
original_hire_dt ,
hispanic_or_latino ,
//initiating_person ,
//initiating_person_id ,
job_code_current ,
job_code_proposed ,
job_family_current ,
job_family_proposed ,
job_family_group_current ,
job_family_group_proposed ,
ltip_bonus_amount ,
ltip_currency ,
last_bonus_dt ,
last_increase_amount ,
last_increase_currency ,
last_increase_percent ,
last_increase_dt ,
legacy_compensation_plans_current ,
legacy_compensation_plans_proposed ,
new_compensation_plans_current ,
new_compensation_plans_proposed ,
line_of_business_current ,
line_of_business_id_current ,
line_of_business_name_current ,
line_of_business_proposed ,
line_of_business_id_proposed ,
line_of_business_name_proposed ,
location_id_current ,
location_name_current ,
location_id_proposed ,
location_name_proposed ,
work_address_city ,
work_address_state ,
work_address_country ,
work_address_postal_code ,
job_exempt_current ,
job_exempt_proposed ,
management_level_current ,
management_level_id_current ,
management_level_proposed ,
management_level_id_proposed ,
supervisory_organization_current ,
supervisory_organization_id_current ,
supervisory_organization_proposed ,
supervisory_organization_id_proposed ,
manager_id_current ,
manager_name_current ,
manager_id_proposed ,
manager_name_proposed ,
manager_job_title_current ,
manager_job_title_proposed ,
manager_work_email_current ,
manager_work_email_proposed ,
direct_report_count ,
span_of_control ,
occ_code_current ,
occ_code_proposed ,
on_leave ,
organization_level_code ,
other_id_legacy_current ,
other_id_legacy_proposed ,
other_id_new_current ,
other_id_new_proposed ,
pay_company_current ,
pay_company_id_current ,
pay_company_name_current ,
pay_company_proposed ,
pay_company_id_proposed ,
pay_company_name_proposed ,
pay_group_id_current ,
pay_group_name_current ,
pay_group_id_proposed ,
pay_group_name_proposed ,
pay_plan ,
planning_manager_current ,
planning_manager_id_current ,
planning_manager_name_current ,
planning_manager_proposed ,
planning_manager_id_proposed ,
planning_manager_name_proposed ,
pre_hire_id ,
pre_hire_wid ,
profit_center_current ,
profit_center_id_current ,
profit_center_name_current ,
profit_center_proposed ,
profit_center_id_proposed ,
profit_center_name_proposed ,
race_ethnicity ,
region_current ,
region_proposed ,
regular_temp ,
sap_company_current ,
sap_company_id_current ,
sap_company_name_current ,
sap_company_proposed ,
sap_company_id_proposed ,
sap_company_name_proposed ,
sony_payroll_company_current ,
sony_payroll_company_id_current ,
sony_payroll_company_name_current ,
sony_payroll_company_proposed ,
sony_payroll_company_id_proposed ,
sony_payroll_company_name_proposed ,
//source ,
union_local_name ,
union_code ,
sub_department_current ,
sub_department_id_current ,
sub_department_name_current ,
sub_department_proposed ,
sub_department_id_proposed ,
sub_department_name_proposed ,
sub_division_current ,
sub_division_id_current ,
sub_division_name_current ,
sub_division_proposed ,
sub_division_id_proposed ,
sub_division_name_proposed ,
termination_dt ,
transaction_status ,
//trended_record_dt ,
veteran_status ,
worker_wid 
from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage where event_wid is not null
) A 
//where event_wid = '80afc79ef2c010021089b4ae2fb60000' 
group by 2,3 having count(*)> 1
;

delete from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage where source_filename = 'outbound/WD_Business_Process_Trans_20240307_hashed.csv';
delete from "PO_STAGE_DB"."Worker".Worker_Transaction_Stage where source_filename = 'outbound/WD_Business_Process_Trans_202205_202208_20240308_hashed.csv';
