
/*
Notes
Line of business remove
Remove EMployee ID nulls.
Candidate ID populated for 2.8k active employees only
Business Unit Unfilled Tony Ken, what is Tom Rothman?
SPlit Management Level
group name or sub group name?
distro email
Job family and family group
Division is wrong for 709965
Saikat change the date to Month beginning instead of end
*/

delete from select max(snapshot_dt) from PO_HRIS_DB."Worker".PO_WORKER_SNAPSHOT where employee_id =
'abfe470ef6e8c353ec4a25561ac9d34db2b40b758d98085d1e520af522bef11e09115c7cca583b47fd8c13b7946063e37ea8d986dc7123b058971d65db1f46bf' and hire_dt = '1992-05-26';


create temp table Corrt_emp_id as
select o.workday_id,o.employee_id as correct_emp_id,d.employee_id as old_emp_id from PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203 o inner join

(select distinct workday_id,employee_id from PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203 where employee_id in (

select distinct employee_id from (select count(*),employee_id,snapshot_dt from PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203  where  snapshot_dt = '2022-12-31' group by 2,3 having count(*)> 1)A 
)
and snapshot_dt = '2022-12-31') d on o.workday_id = d.workday_id where o.snapshot_dt = '2023-01-31';


Update PO_HRIS_DB."Worker".PO_WORKER_SNAPSHOT w
set employee_id = a.correct_emp_id
from Corrt_emp_id a
where w.workday_id = a.workday_id
and w.snapshot_dt <= '2022-12-31';
select email,contingent_worker,contingent_worker_type,* from PO_HRIS_DB."Worker".PO_Worker_Snapshot where snapshot_dt = '2022-12-31' limit 10 ;

truncate table PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage;

select * from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage;
;

copy into PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage
from (select 
$1,
$2,
$3,
$4,
$5,
$6,
$7,
$8,
$9,
$10,
$11,
$12,
$13,
$14,
$15,
$16,
$17,
$18,
$19,
$20,
$21,
$22,
$23,
$24,
$25,
$26,
$27,
$28,
$29,
$30,
$31,
$32,
$33,
$34,
$35,
$36,
$37,
$38,
$39,
$40,
$41,
$42,
$43,
$44,
$45,
$46,
$47,
$48,
$49,
$50,
$51,
$52,
$53,
$54,
$55,
$56,
$57,
$58,
$59,
$60,
$61,
$62,
$63,
$64,
$65,
$66,
$67,
$68,
$69,
$70,
$71,
$72,
$73,
$74,
$75,
$76,
$77,
$78,
$79,
$80,
$81,
$82,
$83,
$84,
$85,
$86,
$87,
$88,
$89,
$90,
$91,
$92,
$93,
$94,
$95,
$96,
$97,
$98,
$99,
$100,
$101,
$102,
$103,
$104,
$105,
$106,
$107,
$108,
$109,
$110,
METADATA$FILENAME
from @PO_STAGE_DB.PUBLIC.MY_S3_STAGE)
pattern = '.*WD_Snapshot_.*20240703_hashed.*'
FILE_FORMAT = (  FORMAT_NAME = 'PO_STAGE_DB."Worker".csv_load_format'  TYPE = CSV ) 
;

select * from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage


delete from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where Source_filename like '%outbound/WD_Snapshot_History_2019-06-30_20231120_hashed.csv%';
delete from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where Source_filename like '%outbound/WD_Snapshot_History_2019-07-31_20231120_hashed.csv%';
delete from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where Source_filename like '%outbound/WD_Snapshot_History_2019-08-31_20231120_hashed.csv%';
delete from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where Source_filename like '%outbound/WD_Snapshot_History_2019-09-30_20231120_hashed.csv%';
delete from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where Source_filename like '%outbound/WD_Snapshot_History_2019-10-31_20231120_hashed.csv%';
delete from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where Source_filename like '%outbound/WD_Snapshot_History_2019-11-30_20231120_hashed.csv%';
delete from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where Source_filename like '%outbound/WD_Snapshot_History_2019-12-31_20231120_hashed.csv%';

--

delete from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where Source_filename like '%WD_Snapshot_History_2023-11-30_20231130_hashed.csv%';
delete from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where Source_filename like '%WD_Snapshot_History_2023-12-31_20231130_hashed.csv%';

delete from PO_HRIS_DB."Worker".PO_Worker_Snapshot where snapshot_dt between '2024-03-31' and '2024-05-31'

//Validation:

select s.employee_id,s.active_status, ss.active_status,s.candidate from PO_HRIS_DB."Worker".PO_Worker_Snapshot s left join PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage ss on s.employee_id =ss.employee_id and ss.snapshot_dt = '2024-03-31' 
where s.snapshot_dt = '2024-03-31'  and s.active_status <> ss.active_status::boolean

and (job_title) like '%EVP, People Organization%'

employee_id = '8cf9a8d854d763ab06ef153aa48ecc3aa70ec82f41d1ce195606092e8453b6fdd3aefda8f6035e265c1c29260b02480b6e96c5af04227b5b1987ac3e8d1e41a0' group by 2;

select count(distinct source_filename) as cnt,snapshot_dt from PO_HRIS_DB."Worker".PO_Worker_Snapshot group by 2 having cnt > 1;

select
max(length(Snapshot_Dt))  ,
max(length(Employee_ID))  ,
max(length(Workday_ID))  ,
max(length(Candidate_ID))  ,
max(length(Candidate))  ,
max(length(Candidate_IDv2))  ,
max(length(Business_Unit))  ,
max(length(Division))  ,
max(length(Sub_Division))  ,
max(length(Dept))  ,
max(length(Sub_Dept))  ,
max(length(Line_of_Business))  ,
max(length(SPE_Business_Unit))  ,
max(length(SPE_Division))  ,
max(length(SPE_Sub_Division))  ,
max(length(SPE_Dept))  ,
max(length(SPE_Sub_Dept))  ,
max(length(Benefit_Code))  ,
max(length(Org_Level))  ,
max(length(Management_Level))  ,
max(length(Hire_Dt))  ,
max(length(Original_Hire_Dt))  ,
max(length(Continuous_Service_Dt))  ,
max(length(Time_in_Job))  ,
max(length(Job_Code))  ,
max(length(Job_Title))  ,
max(length(Job_Family_Func))  ,
max(length(Job_Family_Grp))  ,
max(length(Job_Family))  ,
max(length(Business_Title))  ,
max(length(Exempt))  ,
max(length(FTE ))  ,
max(length(Time_Type))  ,
max(length(Pay_Rate_Type))  ,
max(length(Pay_Frequency))  ,
max(length(Hourly_Rate))  ,
max(length(Hourly_Rate_Currency))  ,
max(length(Annual_Base_Pay))  ,
max(length(Annual_Base_Currency))  ,
max(length(Annual_Base_Pay_US))  ,
max(length(Annual_Base_Currency_US))  ,
max(length(Aspire_Target_Percentage))  ,
max(length(Aspire_Bonus_Plan))  ,
max(length(Aspire_Bonus))  ,
max(length(Aspire_Bonus_Currency))  ,
max(length(Aspire_Bonus_Plan_US))  ,
max(length(Currency1))  ,
max(length(Supervisory_Org))  ,
max(length(Hierarchy_L1))  ,
max(length(Hierarchy_L2))  ,
max(length(Hierarchy_L3))  ,
max(length(Hierarchy_L4))  ,
max(length(Hierarchy_L5))  ,
max(length(Hierarchy_L6))  ,
max(length(Hierarchy_L7))  ,
max(length(Hierarchy_L8))  ,
max(length(Hierarchy_L9))  ,
max(length(Hierarchy_L10))  ,
max(length(Manager_Job_Title))  ,
max(length(Manager_Work_Email))  ,
max(length(Manager_Gender))  ,
max(length(Direct_Reports))  ,
max(length(Span_of_Control))  ,
max(length(Last_Base_Pay_Increase))  ,
max(length(Last_Base_Pay_Increase_Currency))  ,
max(length(Last_Base_Pay_Increase_US))  ,
max(length(Last_Base_Pay_Increase_Dt))  ,
max(length(Last_Base_Pay_Increase_Percent))  ,
max(length(One_Time_Payment_Dt))  ,
max(length(LTIP_Plan_Amt))  ,
max(length(LTIP_Plan_Currency))  ,
max(length(Employee_Type))  ,
max(length(End_Employment_Dt))  ,
max(length(Contingent_Worker))  ,
max(length(Contingent_Worker_Type))  ,
max(length(Union_Local_Code))  ,
max(length(Union_Local_Name))  ,
max(length(Region))  ,
max(length(Work_City))  ,
max(length(Work_State))  ,
max(length(Work_Postal_Code))  ,
max(length(Work_Country))  ,
max(length(Dept_ID))  ,
max(length(Cost_Center))  ,
max(length(Cost_Center_Name))  ,
max(length(Cost_Profit_Center))  ,
max(length(Cost_Profit_Center_ID))  ,
max(length(Cost_Element_Superior))  ,
max(length(Gender))  ,
max(length(Age))  ,
max(length(Hispanic_Latino))  ,
max(length(Race_Ethnicity))  ,
max(length(Vetaran))  ,
max(length(Disbaility))  ,
max(length(Termination_Dt))  ,
max(length(Work_Location))  ,
max(length(Is_Voluntary_FG))  ,
max(length(Business_Partner))  ,
max(length(Generation))  ,
max(length(Pay_Company))  ,
max(length(Base_Pay_Range_Segment))  ,
max(length(Email))  ,
max(length(Active_Status))  ,
max(length(On_Leave))  ,
max(length(Job_Description))  ,
max(length(Salary_Plan))  ,
max(length(Compensation_Grade))  

from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage ;


//stage creation
create or replace TABLE PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_STAGE (
	SNAPSHOT_DT VARCHAR(10),
	EMPLOYEE_ID VARCHAR(128),
	WORKDAY_ID VARCHAR(32),
	CANDIDATE_ID VARCHAR(128),
	CANDIDATE VARCHAR(150),
	CANDIDATE_IDV2 VARCHAR(20),
	BUSINESS_UNIT VARCHAR(40),
	DIVISION VARCHAR(100),
	SUB_DIVISION VARCHAR(100),
	DEPT VARCHAR(80),
	SUB_DEPT VARCHAR(80),
	LINE_OF_BUSINESS VARCHAR(50),
	SPE_BUSINESS_UNIT VARCHAR(50),
	SPE_DIVISION VARCHAR(100),
	SPE_SUB_DIVISION VARCHAR(100),
	SPE_DEPT VARCHAR(80),
	SPE_SUB_DEPT VARCHAR(80),
	BENEFIT_CODE VARCHAR(200),
	ORG_LEVEL VARCHAR(20),
	MANAGEMENT_LEVEL VARCHAR(30),
	HIRE_DT VARCHAR(10),
	ORIGINAL_HIRE_DT VARCHAR(10),
	IS_REHIRE VARCHAR(10),
	CONTINUOUS_SERVICE_DT VARCHAR(10),
	TIME_IN_JOB VARCHAR(100),
	JOB_CODE VARCHAR(140),
	JOB_TITLE VARCHAR(120),
	JOB_FAMILY_FUNC VARCHAR(100),
	JOB_FAMILY_GRP VARCHAR(60),
	JOB_FAMILY VARCHAR(90),
	BUSINESS_TITLE VARCHAR(130),
	EXEMPT VARCHAR(10),
	FTE VARCHAR(10),
	TIME_TYPE VARCHAR(10),
	PAY_RATE_TYPE VARCHAR(20),
	PAY_FREQUENCY VARCHAR(30),
	HOURLY_RATE VARCHAR(10),
	HOURLY_RATE_CURRENCY VARCHAR(10),
	ANNUAL_BASE_PAY VARCHAR(20),
	ANNUAL_BASE_CURRENCY VARCHAR(10),
	ANNUAL_BASE_PAY_US VARCHAR(10),
	ANNUAL_BASE_CURRENCY_US VARCHAR(10),
	ASPIRE_TARGET_PERCENTAGE VARCHAR(10),
	ASPIRE_BONUS_PLAN VARCHAR(120),
	ASPIRE_BONUS VARCHAR(20),
	ASPIRE_BONUS_CURRENCY VARCHAR(10),
	ASPIRE_BONUS_PLAN_US VARCHAR(200),
	CURRENCY1 VARCHAR(10),
	SUPERVISORY_ORG VARCHAR(128),
	HIERARCHY_L1 VARCHAR(40),
	HIERARCHY_L2 VARCHAR(40),
	HIERARCHY_L3 VARCHAR(40),
	HIERARCHY_L4 VARCHAR(40),
	HIERARCHY_L5 VARCHAR(30),
	HIERARCHY_L6 VARCHAR(30),
	HIERARCHY_L7 VARCHAR(20),
	HIERARCHY_L8 VARCHAR(20),
	HIERARCHY_L9 VARCHAR(20),
	HIERARCHY_L10 VARCHAR(20),
	MANAGER_JOB_TITLE VARCHAR(120),
	MANAGER_WORK_EMAIL VARCHAR(128),
	MANAGER_GENDER VARCHAR(100),
	DIRECT_REPORTS VARCHAR(10),
	SPAN_OF_CONTROL VARCHAR(10),
	LAST_BASE_PAY_INCREASE VARCHAR(20),
	LAST_BASE_PAY_INCREASE_CURRENCY VARCHAR(10),
	LAST_BASE_PAY_INCREASE_US VARCHAR(20),
	LAST_BASE_PAY_INCREASE_DT VARCHAR(10),
	LAST_BASE_PAY_INCREASE_PERCENT VARCHAR(10),
	ONE_TIME_PAYMENT_DT VARCHAR(10),
	LTIP_PLAN_AMT VARCHAR(10),
	LTIP_PLAN_CURRENCY VARCHAR(10),
	EMPLOYEE_TYPE VARCHAR(30),
	END_EMPLOYMENT_DT VARCHAR(10),
	CONTINGENT_WORKER VARCHAR(40),
	CONTINGENT_WORKER_TYPE VARCHAR(30),
	UNION_LOCAL_CODE VARCHAR(500),
	UNION_LOCAL_NAME VARCHAR(500),
	REGION VARCHAR(20),
	WORK_CITY VARCHAR(30),
	WORK_STATE VARCHAR(40),
	WORK_POSTAL_CODE VARCHAR(20),
	WORK_COUNTRY VARCHAR(30),
	DEPT_ID VARCHAR(10),
	COST_CENTER VARCHAR(60),
	COST_CENTER_NAME VARCHAR(60),
	COST_PROFIT_CENTER VARCHAR(60),
	COST_PROFIT_CENTER_ID VARCHAR(110),
	COST_ELEMENT_SUPERIOR VARCHAR(20),
	GENDER VARCHAR(100),
	AGE VARCHAR(10),
	HISPANIC_LATINO VARCHAR(10),
	RACE_ETHNICITY VARCHAR(100),
	VETARAN VARCHAR(70),
	DISBAILITY VARCHAR(60),
	TERMINATION_DT VARCHAR(10),
	TERMINATION_DT_ALL VARCHAR(10),
	TERMINATION_PRIMARY VARCHAR(100),
	WORK_LOCATION VARCHAR(500),
	IS_VOLUNTARY_FG VARCHAR(10),
	BUSINESS_PARTNER VARCHAR(30),
	GENERATION VARCHAR(40),
	PAY_COMPANY VARCHAR(50),
	BASE_PAY_RANGE_SEGMENT VARCHAR(20),
	EMAIL VARCHAR(130),
	ACTIVE_STATUS VARCHAR(10),
	ON_LEAVE VARCHAR(3),
	JOB_DESCRIPTION VARCHAR(16777216),
	SALARY_PLAN VARCHAR(90),
	COMPENSATION_GRADE VARCHAR(30),
	SOURCE_FILENAME VARCHAR(200)
);


//final table
CREATE OR REPLACE TABLE PO_HRIS_DB."Worker".PO_Worker_Snapshot
(
Snapshot_Dt Date not null,
Employee_ID Varchar(128) not null,
Workday_ID Varchar(32) not null,
Candidate_ID Varchar(128),
Candidate Varchar(150),
//Candidate_IDv2 Varchar(20),
Hire_Dt Date not null,
Original_Hire_Dt Date not null,
Continuous_Service_Dt Date ,
Termination_Dt Date,
Termination_Dt_all Date,
Termination_Dt_Primary Date,
Termination_Reason Varchar(200),
Is_Rehire Varchar(10),
Business_Unit Varchar(40),
Division Varchar(100),
Sub_Division Varchar(100),
Dept Varchar(80),
Sub_Dept Varchar(80),
Line_of_Business Varchar(30),
SPE_Business_Unit Varchar(50),
SPE_Division Varchar(100),
SPE_Sub_Division Varchar(100),
SPE_Dept Varchar(80),
SPE_Sub_Dept Varchar(80),
Benefit_Code Varchar(50),
Org_Level Varchar(20),
Management_Level Varchar(30),
Time_in_Job Varchar(100),
Job_Code Varchar(128),
Job_Title Varchar(120),
Job_Family_Func Varchar(30),
Job_Family_Grp Varchar(60),
Job_Family Varchar(90),
Business_Title Varchar(130),
Exempt Varchar(10),
FTE  Varchar(10),
Time_Type Varchar(10),
Pay_Rate_Type Varchar(20),
Pay_Frequency Varchar(30),
Hourly_Rate Number,
Hourly_Rate_Currency Varchar(10),
Annual_Base_Pay Number(20,2),
Annual_Base_Currency Varchar(10),
Annual_Base_Pay_US Number(20,2),
//Annual_Base_Currency_US Varchar(10),
Aspire_Target_Percentage Varchar(10),
Aspire_Bonus_Plan Varchar(120),
Aspire_Bonus Number(20,2),
Aspire_Bonus_Currency Varchar(10),
Aspire_Bonus_Plan_US Number(20,2),
//Currency1 Varchar(10),
Supervisory_Org Varchar(128),
Hierarchy_L1 Varchar(40),
Hierarchy_L2 Varchar(40),
Hierarchy_L3 Varchar(40),
Hierarchy_L4 Varchar(40),
Hierarchy_L5 Varchar(30),
Hierarchy_L6 Varchar(30),
Hierarchy_L7 Varchar(20),
Hierarchy_L8 Varchar(20),
Hierarchy_L9 Varchar(20),
Hierarchy_L10 Varchar(20),
Manager_Job_Title Varchar(120),
Manager_Work_Email Varchar(128),
Manager_Gender Varchar(100),
Direct_Reports Varchar(10),
Span_of_Control Varchar(10),
Last_Base_Pay_Increase Number(20,2),
Last_Base_Pay_Increase_Currency Varchar(10),
Last_Base_Pay_Increase_US Number(20,2),
Last_Base_Pay_Increase_Dt Date,
Last_Base_Pay_Increase_Percent Varchar(10),
One_Time_Payment_Dt Date,
LTIP_Plan_Amt Number(20,2),
LTIP_Plan_Currency Varchar(10),
Employee_Type Varchar(30),
End_Employment_Dt Date,
Contingent_Worker Varchar(40),
Contingent_Worker_Type Varchar(30),
Union_Local_Code Varchar(100),
Union_Local_Name Varchar(100),
Region Varchar(20),
Work_City Varchar(30),
Work_State Varchar(40),
Work_Postal_Code Varchar(20),
Work_Country Varchar(30),
Dept_ID Varchar(10),
Cost_Center Varchar(60),
Cost_Center_Name Varchar(60),
Cost_Profit_Center Varchar(60),
Cost_Profit_Center_ID Varchar(110),
Cost_Element_Superior Varchar(20),
Gender Varchar(30),
Age Varchar(10),
Hispanic_Latino Varchar(10),
Race_Ethnicity Varchar(100),
Vetaran Varchar(70),
Disbaility Varchar(60),
Work_Location Varchar(200),
Is_Voluntary_FG Boolean,
Business_Partner Varchar(30),
Generation Varchar(40),
Pay_Company Varchar(50),
Base_Pay_Range_Segment Varchar(20),
Email Varchar(130),
Active_Status Boolean,
On_Leave Varchar(3),
Job_Description Varchar,
Salary_Plan Varchar(90),
Compensation_Grade Varchar(30),
Source_FileName Varchar(200),
Created_Date timestamp_ntz,
Created_By Varchar(100),
Modified_Date timestamp_ntz,
Modifeid_By Varchar(100),
Batch_ID Integer
)
DATA_RETENTION_TIME_IN_DAYS = 7
COMMENT = 'Worker mnothly snapshot data';

select distinct snapshot_dt from PO_HRIS_DB."Worker".PO_Worker_Snapshot where snapshot_dt >= '2024-04-18';

INSERT INTO PO_HRIS_DB."Worker".PO_Worker_Snapshot
(
 Snapshot_Dt  ,
Employee_ID  ,
Workday_ID  ,
Candidate_ID  ,
Candidate  ,
Business_Unit  ,
Division  ,
Sub_Division  ,
Dept  ,
Sub_Dept  ,
--Line_of_Business  ,
SPE_Business_Unit  ,
SPE_Division  ,
SPE_Sub_Division  ,
SPE_Dept  ,
SPE_Sub_Dept  ,
Benefit_Code  ,
Org_Level  ,
Management_Level  ,
Hire_Dt  ,
Original_Hire_Dt  ,
Continuous_Service_Dt  ,
Time_in_Job  ,
Job_Code  ,
Job_Title  ,
Job_Family_Func  ,
Job_Family_Grp  ,
Job_Family  ,
Business_Title  ,
Exempt  ,
FTE   ,
Time_Type  ,
Pay_Rate_Type  ,
Pay_Frequency  ,
Hourly_Rate  ,
Hourly_Rate_Currency  ,
Annual_Base_Pay  ,
Annual_Base_Currency  ,
Annual_Base_Pay_US  ,
Aspire_Target_Percentage  ,
Aspire_Bonus_Plan  ,
Aspire_Bonus  ,
Aspire_Bonus_Currency  ,
Aspire_Bonus_Plan_US  ,
Supervisory_Org  ,
Hierarchy_L1  ,
Hierarchy_L2  ,
Hierarchy_L3  ,
Hierarchy_L4  ,
Hierarchy_L5  ,
Hierarchy_L6  ,
Hierarchy_L7  ,
Hierarchy_L8  ,
Hierarchy_L9  ,
Hierarchy_L10  ,
Manager_Job_Title  ,
Manager_Work_Email  ,
Manager_Gender  ,
Direct_Reports  ,
Span_of_Control  ,
Last_Base_Pay_Increase  ,
Last_Base_Pay_Increase_Currency  ,
Last_Base_Pay_Increase_US  ,
Last_Base_Pay_Increase_Dt  ,
Last_Base_Pay_Increase_Percent  ,
One_Time_Payment_Dt  ,
LTIP_Plan_Amt  ,
LTIP_Plan_Currency  ,
Employee_Type  ,
End_Employment_Dt  ,
Contingent_Worker  ,
Contingent_Worker_Type  ,
Union_Local_Code  ,
Union_Local_Name  ,
Region  ,
Work_City  ,
Work_State  ,
Work_Postal_Code  ,
Work_Country  ,
Dept_ID  ,
Cost_Center  ,
Cost_Center_Name  ,
Cost_Profit_Center  ,
Cost_Profit_Center_ID  ,
Cost_Element_Superior  ,
Gender  ,
Age  ,
Hispanic_Latino  ,
Race_Ethnicity  ,
Vetaran  ,
Disbaility  ,
Termination_Dt  ,
Work_Location  ,
Is_Voluntary_FG  ,
Business_Partner  ,
Generation  ,
Pay_Company  ,
Base_Pay_Range_Segment  ,
Email  ,
Active_Status  ,
On_Leave  ,
Job_Description  ,
Salary_Plan  ,
Compensation_Grade,
Termination_Dt_all,
Termination_Reason,
Is_Rehire,
SOURCE_FILENAME,
Created_Date ,
Created_By ,
Modified_Date ,
Modifeid_By ,
Batch_ID 
)
SELECT
Snapshot_Dt  ,
Employee_ID  ,
Workday_ID  ,
replace (Candidate_ID,'17ea18adaf471a26e57a5091f0a51eba3d04a6b7d52331171bf33f2ea6ecd5437edf71c62e15b5f1cdbc3252c12ed57e296011f2af8b58631dbacbe166ff0b74'),
Candidate  ,
Business_Unit  ,
Division  ,
Sub_Division  ,
Dept  ,
Sub_Dept  ,
--Line_of_Business  ,
SPE_Business_Unit  ,
SPE_Division  ,
SPE_Sub_Division  ,
SPE_Dept  ,
SPE_Sub_Dept  ,
Benefit_Code  ,
Org_Level  ,
Management_Level  ,
Hire_Dt  ,
Original_Hire_Dt  ,
Continuous_Service_Dt  ,
Time_in_Job  ,
Job_Code  ,
Job_Title  ,
Job_Family_Func  ,
Job_Family_Grp  ,
Job_Family  ,
Business_Title  ,
Exempt  ,
FTE   ,
Time_Type  ,
Pay_Rate_Type  ,
Pay_Frequency  ,
Hourly_Rate  ,
Hourly_Rate_Currency  ,
Annual_Base_Pay  ,
Annual_Base_Currency  ,
Annual_Base_Pay_US  ,
Aspire_Target_Percentage  ,
Aspire_Bonus_Plan  ,
Aspire_Bonus  ,
Aspire_Bonus_Currency  ,
Aspire_Bonus_Plan_US  ,
Supervisory_Org  ,
Hierarchy_L1  ,
Hierarchy_L2  ,
Hierarchy_L3  ,
Hierarchy_L4  ,
Hierarchy_L5  ,
Hierarchy_L6  ,
Hierarchy_L7  ,
Hierarchy_L8  ,
Hierarchy_L9  ,
Hierarchy_L10  ,
Manager_Job_Title  ,
Manager_Work_Email  ,
Manager_Gender  ,
Direct_Reports  ,
Span_of_Control  ,
Last_Base_Pay_Increase  ,
Last_Base_Pay_Increase_Currency  ,
Last_Base_Pay_Increase_US  ,
Last_Base_Pay_Increase_Dt  ,
Last_Base_Pay_Increase_Percent  ,
One_Time_Payment_Dt  ,
LTIP_Plan_Amt  ,
LTIP_Plan_Currency  ,
Employee_Type  ,
End_Employment_Dt  ,
Contingent_Worker  ,
Contingent_Worker_Type  ,
Union_Local_Code  ,
Union_Local_Name  ,
Region  ,
Work_City  ,
Work_State  ,
Work_Postal_Code  ,
Work_Country  ,
Dept_ID  ,
Cost_Center  ,
Cost_Center_Name  ,
Cost_Profit_Center  ,
Cost_Profit_Center_ID  ,
Cost_Element_Superior  ,
Gender  ,
Age  ,
Hispanic_Latino  ,
Race_Ethnicity  ,
Vetaran  ,
Disbaility  ,
Termination_Dt  ,
Work_Location  ,
Is_Voluntary_FG  ,
Business_Partner  ,
Generation  ,
Pay_Company  ,
Base_Pay_Range_Segment  ,
Email  ,
Active_Status  ,
On_Leave  ,
Job_Description  ,
Salary_Plan  ,
Compensation_Grade,
Termination_Dt_all,
Termination_Primary,
Is_Rehire,
trim(substr(SOURCE_FILENAME,position('/',SOURCE_FILENAME,1)+1, 60)),
//SOURCE_FILENAME,
   CURRENT_TIMESTAMP,
   CURRENT_USER,
     CURRENT_TIMESTAMP,
   CURRENT_USER,
   20240610
FROM PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage ;