

insert into PO_HRIS_DB."Worker".PO_Worker_Snapshot 
(
SNAPSHOT_DT,
	EMPLOYEE_ID,
	WORKDAY_ID,
	CANDIDATE_ID,
	CANDIDATE,
	HIRE_DT,
	ORIGINAL_HIRE_DT,
	CONTINUOUS_SERVICE_DT,
	TERMINATION_DT,
	TERMINATION_DT_ALL,
	TERMINATION_REASON,
	IS_REHIRE,
	BUSINESS_UNIT,
	DIVISION,
	SUB_DIVISION,
	DEPT,
	SUB_DEPT,
	LINE_OF_BUSINESS,
	SPE_BUSINESS_UNIT,
	SPE_DIVISION,
	SPE_SUB_DIVISION,
	SPE_DEPT,
	SPE_SUB_DEPT,
	BENEFIT_CODE,
	ORG_LEVEL,
	MANAGEMENT_LEVEL,
	TIME_IN_JOB,
	JOB_CODE,
	JOB_TITLE,
	JOB_FAMILY_FUNC,
	JOB_FAMILY_GRP,
	JOB_FAMILY,
	BUSINESS_TITLE,
	EXEMPT,
	FTE,
	TIME_TYPE,
	PAY_RATE_TYPE,
	PAY_FREQUENCY,
	HOURLY_RATE,
	HOURLY_RATE_CURRENCY,
	ANNUAL_BASE_PAY,
	ANNUAL_BASE_CURRENCY,
	ANNUAL_BASE_PAY_US,
	ASPIRE_TARGET_PERCENTAGE,
	ASPIRE_BONUS_PLAN,
	ASPIRE_BONUS,
	ASPIRE_BONUS_CURRENCY,
	ASPIRE_BONUS_PLAN_US,
	SUPERVISORY_ORG,
	HIERARCHY_L1,
	HIERARCHY_L2,
	HIERARCHY_L3,
	HIERARCHY_L4,
	HIERARCHY_L5,
	HIERARCHY_L6,
	HIERARCHY_L7,
	HIERARCHY_L8,
	HIERARCHY_L9,
	HIERARCHY_L10,
	MANAGER_JOB_TITLE,
	MANAGER_WORK_EMAIL,
	MANAGER_GENDER,
	DIRECT_REPORTS,
	SPAN_OF_CONTROL,
	LAST_BASE_PAY_INCREASE,
	LAST_BASE_PAY_INCREASE_CURRENCY,
	LAST_BASE_PAY_INCREASE_US,
	LAST_BASE_PAY_INCREASE_DT,
	LAST_BASE_PAY_INCREASE_PERCENT,
	ONE_TIME_PAYMENT_DT,
	LTIP_PLAN_AMT,
	LTIP_PLAN_CURRENCY,
	EMPLOYEE_TYPE,
	END_EMPLOYMENT_DT,
	CONTINGENT_WORKER,
	CONTINGENT_WORKER_TYPE,
	UNION_LOCAL_CODE,
	UNION_LOCAL_NAME,
	REGION,
	WORK_CITY,
	WORK_STATE,
	WORK_POSTAL_CODE,
	WORK_COUNTRY,
	DEPT_ID,
	COST_CENTER,
	COST_CENTER_NAME,
	COST_PROFIT_CENTER,
	COST_PROFIT_CENTER_ID,
	COST_ELEMENT_SUPERIOR,
	GENDER,
	AGE,
	HISPANIC_LATINO,
	RACE_ETHNICITY,
	VETARAN,
	DISBAILITY,
	WORK_LOCATION,
	IS_VOLUNTARY_FG,
	BUSINESS_PARTNER,
	GENERATION,
	PAY_COMPANY,
	BASE_PAY_RANGE_SEGMENT,
	EMAIL,
	ACTIVE_STATUS,
	ON_LEAVE,
	JOB_DESCRIPTION,
	SALARY_PLAN,
	COMPENSATION_GRADE,
	SOURCE_FILENAME,
	CREATED_DATE,
	CREATED_BY,
	MODIFIED_DATE,
	MODIFEID_BY,
	BATCH_ID
)

select 
SNAPSHOT_DT,
	EMPLOYEE_ID,
	WORKDAY_ID,
	CANDIDATE_ID,
	CANDIDATE,
	HIRE_DT,
	ORIGINAL_HIRE_DT,
	CONTINUOUS_SERVICE_DT,
	TERMINATION_DT,
	TERMINATION_DT_ALL,
	TERMINATION_REASON,
	IS_REHIRE,
	BUSINESS_UNIT,
	DIVISION,
	SUB_DIVISION,
	DEPT,
	SUB_DEPT,
	LINE_OF_BUSINESS,
	SPE_BUSINESS_UNIT,
	SPE_DIVISION,
	SPE_SUB_DIVISION,
	SPE_DEPT,
	SPE_SUB_DEPT,
	BENEFIT_CODE,
	ORG_LEVEL,
	MANAGEMENT_LEVEL,
	TIME_IN_JOB,
	JOB_CODE,
	JOB_TITLE,
	JOB_FAMILY_FUNC,
	JOB_FAMILY_GRP,
	JOB_FAMILY,
	BUSINESS_TITLE,
	EXEMPT,
	FTE,
	TIME_TYPE,
	PAY_RATE_TYPE,
	PAY_FREQUENCY,
	HOURLY_RATE,
	HOURLY_RATE_CURRENCY,
	ANNUAL_BASE_PAY,
	ANNUAL_BASE_CURRENCY,
	ANNUAL_BASE_PAY_US,
	ASPIRE_TARGET_PERCENTAGE,
	ASPIRE_BONUS_PLAN,
	ASPIRE_BONUS,
	ASPIRE_BONUS_CURRENCY,
	ASPIRE_BONUS_PLAN_US,
	SUPERVISORY_ORG,
	HIERARCHY_L1,
	HIERARCHY_L2,
	HIERARCHY_L3,
	HIERARCHY_L4,
	HIERARCHY_L5,
	HIERARCHY_L6,
	HIERARCHY_L7,
	HIERARCHY_L8,
	HIERARCHY_L9,
	HIERARCHY_L10,
	MANAGER_JOB_TITLE,
	MANAGER_WORK_EMAIL,
	MANAGER_GENDER,
	DIRECT_REPORTS,
	SPAN_OF_CONTROL,
	LAST_BASE_PAY_INCREASE,
	LAST_BASE_PAY_INCREASE_CURRENCY,
	LAST_BASE_PAY_INCREASE_US,
	LAST_BASE_PAY_INCREASE_DT,
	LAST_BASE_PAY_INCREASE_PERCENT,
	ONE_TIME_PAYMENT_DT,
	LTIP_PLAN_AMT,
	LTIP_PLAN_CURRENCY,
	EMPLOYEE_TYPE,
	END_EMPLOYMENT_DT,
	CONTINGENT_WORKER,
	CONTINGENT_WORKER_TYPE,
	UNION_LOCAL_CODE,
	UNION_LOCAL_NAME,
	REGION,
	WORK_CITY,
	WORK_STATE,
	WORK_POSTAL_CODE,
	WORK_COUNTRY,
	DEPT_ID,
	COST_CENTER,
	COST_CENTER_NAME,
	COST_PROFIT_CENTER,
	COST_PROFIT_CENTER_ID,
	COST_ELEMENT_SUPERIOR,
	GENDER,
	AGE,
	HISPANIC_LATINO,
	RACE_ETHNICITY,
	VETARAN,
	DISBAILITY,
	WORK_LOCATION,
	IS_VOLUNTARY_FG,
	BUSINESS_PARTNER,
	GENERATION,
	PAY_COMPANY,
	BASE_PAY_RANGE_SEGMENT,
	EMAIL,
	ACTIVE_STATUS,
	ON_LEAVE,
	JOB_DESCRIPTION,
	SALARY_PLAN,
	COMPENSATION_GRADE,
	SOURCE_FILENAME,
	CREATED_DATE,
	CREATED_BY,
	MODIFIED_DATE,
	MODIFEID_BY,
	BATCH_ID
from PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203 where snapshot_dt >= '2022-03-31'  and snapshot_dt <= '2022-12-31';


select  termination_reason,* from PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203 where snapshot_dt = '2023-10-31' and active_status = 'False'

select * from PO_HRIS_DB."Application".PO_WD_CANDIDATE;

select 
employee_type,union_local_name,benefit_code,et_file,contingent_worker_type,ss.* from PO_HRIS_DB."Worker".PO_Worker_Snapshot ss inner join
(select lpad(o.employee_id,8,0) as d_ido,o.employee_type as et_file
 from PO_STAGE_DB."Worker".wd_hist_from_file o
Left join (select lpad(employee_id,8,0) d_id,* from PO_STAGE_DB."Worker".wd_hist_from_file where FY_YY_QQ = 'FY 24 Q4') n on o.employee_id = n.employee_id
where o.FY_YY_QQ = 'FY 24 Q3' and n.employee_id is null) aa on ss.employee_id = aa.d_ido
where snapshot_dt = '2024-04-18' and active_status and hire_dt <= '2024-04-01';


create or replace table PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_NewWDData as 
select * from PO_HRIS_DB."Worker".PO_Worker_Snapshot 
where snapshot_dt >= '2022-03-31' ;

delete from PO_HRIS_DB."Worker".PO_Worker_Snapshot 
where snapshot_dt >= '2022-03-31'  and snapshot_dt <= '2022-12-31'

and EMPLOYEE_TYPE IN ('Regular', 'Limited Term') and active_status
and ifnull(REGEXP_SUBSTR(benefit_code, '^[[:alnum:]]+'),'EM') IN  ('A1','A5','B3','B4','C1','I2','I3','I5','N4','N6','VA1','VA6','VB3','EM')


select distinct snapshot_dt from PO_HRIS_DB."Worker".PO_Worker_Snapshot 
where snapshot_dt >= '2024-01-31' and EMPLOYEE_TYPE IN ('Regular','Contract - CATS' ,'Limited Term','Wholly Owned Subsidiary','Union',
'Union-Limited Term') and active_status
and ifnull(REGEXP_SUBSTR(benefit_code, '^[[:alnum:]]+'),'EM') IN  ('A1','A5','B3','B4','C1','I2','I3','I5','N4','N6','VA1','VA6','VB3','EM')
;
select o.benefit_code,n.benefit_code,* from PO_HRIS_DB."Worker".PO_WORKER_SNAPSHOT o
left join PO_HRIS_DB."Worker".PO_Worker_Snapshot n on o.employee_id = n.employee_id and n.snapshot_dt = '2022-12-31'
//left join PO_HRIS_DB."Worker".WORKER_TRANSACTION_TYPE t on t.employee_id = o.employee_id and business_process_type like '%Termination%' 
//and effective_dt between '2022-12-31' and '2023-01-31'
where o.snapshot_dt = '2022-12-31' 
and o.active_status
and  n.employee_id is null; and t.employee_id is null ;

--33 contingent workers are dropped in legacy system on 01/31/2023 compared to 12/31/2022

select o.benefit_code,n.benefit_code,* from PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203 o
left join PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203 n on o.employee_id = n.employee_id and n.snapshot_dt = '2023-01-31'
//left join PO_HRIS_DB."Worker".WORKER_TRANSACTION_TYPE t on t.employee_id = o.employee_id and business_process_type like '%Termination%' 
//and effective_dt between '2022-12-31' and '2023-01-31'
where o.snapshot_dt = '2022-12-31' 
and o.active_status
and  n.employee_id is null;

//113 employees active but not migrated into new system out of 240;
// 
select employee_id,active_status,employee_type,benefit_code,* from 
//PO_HRIS_DB."Worker".PO_Worker_Snapshot  
PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203
where employee_id in (
select distinct s.employee_id from 
PO_HRIS_DB."Worker".PO_Worker_Snapshot s
left join  PO_HRIS_DB."Worker".PO_WORKER_SNAPSHOT n  on s.employee_id = n.employee_id and n.snapshot_dt = '2023-01-31'
where s.snapshot_dt = '2022-12-31' and n.employee_id is null and s.active_status
) and snapshot_dt = '2023-10-31' and active_status ;and is_rehire = 0;



select s.employee_type,n.employee_type,s.contingent_worker_type,n.contingent_worker_type,s.job_family,s.job_family_grp,s.union_local_name,n.union_local_name,s.end_employment_dt,s.compensation_grade,n.compensation_grade,n.batch_id,* from 
PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203 s
left join  PO_HRIS_DB."Worker".PO_WORKER_SNAPSHOT n  on s.employee_id = n.employee_id and n.snapshot_dt = '2023-11-30'
where s.snapshot_dt = '2023-10-31' and s.active_status 
//and s.employee_type like '%Joint%'--jv9999 comp grade = regular and contingent worker type = 'JV' and end emp date is null then JV emp type else JV -Limited term (try job family B-GEN)
and s.employee_type like '%Wholly%'
//and s.union_local_name is not null
and n.employee_type in ('Regular');




select count(*),active_status,snapshot_dt from
(select snapshot_dt,employee_id,active_status,employee_type,contingent_worker,contingent_worker_type,hire_dt from PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203  where snapshot_dt <= '2022-12-31' and EMPLOYEE_TYPE IN ('Regular','Contract - CATS' ,'Limited Term','Wholly Owned Subsidiary','Union',
'Union-Limited Term') and active_status
and ifnull(REGEXP_SUBSTR(benefit_code, '^[[:alnum:]]+'),'EM') IN  ('A1','A5','B3','B4','C1','I2','I3','I5','N4','N6','VA1','VA6','VB3','EM')
union all
select snapshot_dt,employee_id,active_status,employee_type,contingent_worker,contingent_worker_type,hire_dt from PO_HRIS_DB."Worker".PO_Worker_Snapshot  where snapshot_dt > '2022-12-31'
and EMPLOYEE_TYPE IN ('Regular','Contract - CATS' ,'Limited Term','Wholly Owned Subsidiary','Union',
'Union-Limited Term') and active_status
and ifnull(REGEXP_SUBSTR(benefit_code, '^[[:alnum:]]+'),'EM') IN  ('A1','A5','B3','B4','C1','I2','I3','I5','N4','N6','VA1','VA6','VB3','EM')
)a where snapshot_dt >= '2021-01-31' group by 2,3;


select count(*),snapshot_dt,contingent_worker_type from PO_HRIS_DB."Worker".PO_Worker_Snapshot  where snapshot_dt > '2021-01-01'
//and EMPLOYEE_TYPE IN ('Regular','Contract - CATS' ,'Limited Term','Wholly Owned Subsidiary','Union',
//'Union-Limited Term') 
and active_status
//and ifnull(REGEXP_SUBSTR(benefit_code, '^[[:alnum:]]+'),'EM') IN  ('A1','A5','B3','B4','C1','I2','I3','I5','N4','N6','VA1','VA6','VB3','EM')
group by 2,3 order by 2

PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203

;


 select * from PO_STAGE_DB."Worker".wd_hist_from_file where fy_yy_qq = 'FY 22 Q3'

 
create table wd_hist_from_file 
(
Employee_ID Varchar,
LastName Varchar,
FirstName Varchar,
Business_Title Varchar,
Business_Unit Varchar,
Division  Varchar,
Sub_Division  Varchar,
Dept Varchar,
Sub_Group  Varchar,
 City Varchar,
Country Varchar,
Region Varchar,
Benefit_Code Varchar,
Employee_Type Varchar,
Org_Level Varchar,
 Business_Partner Varchar,
Manager Varchar,
Gender Varchar,
Race_Ethnicity Varchar,
tenure Varchar,
Generation Varchar,
Canada_Code Varchar,
Job_Family Varchar,
Job_Family_Group Varchar,
FY_YY Varchar,
FY_QQ Varchar,
FY_YY_QQ Varchar,
Effective_Date Varchar
);



select 
distinct  termination_reason from PO_HRIS_DB."Worker".PO_Worker_Snapshot --group by 1 order by 1 desc;
where snapshot_dt >= '2024-04-18'; and active_status

and employee_type = 'Regular' 

and benefit_code = 'A3 Term Deal US' ;and job_code = 'D-LGT-P3N-03' and hire_dt > '2021-01-01';

where workday_id = '0e05a69c31244c5a9f4dc4efd54e772d'

End Contingent Worker Contract > Voluntary > Contract Ended



snapshot_dt >= '2022-12-31' limit 10;

delete from PO_HRIS_DB."Worker".PO_Worker_Snapshot where snapshot_dt in (select distinct snapshot_dt  from PO_HRIS_DB."Worker".PO_Worker_Snapshot 
where snapshot_dt > '2022-02-28' and snapshot_dt <= '2023-10-31' )
;
truncate table PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage;
show tasks

alter task t_wd_snapshot_load resume;

/*Task for Newhire*/
create or replace task PO_HRIS_DB."Worker".t_wd_snapshot_load
Warehouse = po_wh
SCHEDULE = 'USING CRON 15 06 * * * America/Chicago'
as 
Call sp_wd_snapshot_load ((to_char(current_date,'YYYYMMDD') )::int)
;


--Race/ethic
select max(snapshot_dt)

from PO_HRIS_DB."Worker".PO_Worker_Snapshot  where snapshot_dt = '2024-05-29' and work_country = 'United States of America' and active_status and contingent_worker_type is null group by 1;

select count(*) from 
PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203 s where snapshot_dt = '2023-09-30' 
--and work_country = 'United States of America' 
and active_status
--and contingent_worker_type is null
and ifnull(benefit_code,'abc') NOT IN ('N1','N3','A3','A4','A9','A8','B4','B5','B6','N7','A2','A6','N5') and employee_type IN ('Contract - CATS','Limited Term','Regular','Union','Union-Limited Term','Wholly Owned Subsidiary') 
group by 1;



ALTER TABLE PO_Worker_Snapshot ALTER LINE_OF_BUSINESS SET DATA TYPE VARCHAR(50);

CREATE OR REPLACE PROCEDURE sp_wd_snapshot_load(Filedate int)
  RETURNS VARCHAR
  LANGUAGE SQL
  EXECUTE AS CALLER
  AS
  $$
  
declare
record_date date;
created_datetime timestamp;
modified_datetime timestamp;
created_by string;
modified_by string;
max_date_stg date;
max_date date;
batch_id int;

begin


record_date := current_date();
created_datetime := current_timestamp(); 
modified_datetime := current_timestamp(); 
created_by := current_user();
modified_by :=  current_user();
select ((to_char(current_date -1,'YYYYMMDD') )::int) into batch_id;

truncate table PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage;

let ins_statement:= 
'
INSERT INTO PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage
(
SNAPSHOT_DT,
EMPLOYEE_ID,
WORKDAY_ID,
CANDIDATE_ID,
CANDIDATE,
CANDIDATE_IDV2,
BUSINESS_UNIT,
DIVISION,
SUB_DIVISION,
DEPT,
SUB_DEPT,
LINE_OF_BUSINESS,
SPE_BUSINESS_UNIT,
SPE_DIVISION,
SPE_SUB_DIVISION,
SPE_DEPT,
SPE_SUB_DEPT,
BENEFIT_CODE,
ORG_LEVEL,
MANAGEMENT_LEVEL,
HIRE_DT,
ORIGINAL_HIRE_DT,
IS_REHIRE,
CONTINUOUS_SERVICE_DT,
TIME_IN_JOB,
JOB_CODE,
JOB_TITLE,
JOB_FAMILY_FUNC,
JOB_FAMILY_GRP,
JOB_FAMILY,
BUSINESS_TITLE,
EXEMPT,
FTE,
TIME_TYPE,
PAY_RATE_TYPE,
PAY_FREQUENCY,
HOURLY_RATE,
HOURLY_RATE_CURRENCY,
ANNUAL_BASE_PAY,
ANNUAL_BASE_CURRENCY,
ANNUAL_BASE_PAY_US,
ANNUAL_BASE_CURRENCY_US,
ASPIRE_TARGET_PERCENTAGE,
ASPIRE_BONUS_PLAN,
ASPIRE_BONUS,
ASPIRE_BONUS_CURRENCY,
ASPIRE_BONUS_PLAN_US,
CURRENCY1,
SUPERVISORY_ORG,
HIERARCHY_L1,
HIERARCHY_L2,
HIERARCHY_L3,
HIERARCHY_L4,
HIERARCHY_L5,
HIERARCHY_L6,
HIERARCHY_L7,
HIERARCHY_L8,
HIERARCHY_L9,
HIERARCHY_L10,
MANAGER_JOB_TITLE,
MANAGER_WORK_EMAIL,
MANAGER_GENDER,
DIRECT_REPORTS,
SPAN_OF_CONTROL,
LAST_BASE_PAY_INCREASE,
LAST_BASE_PAY_INCREASE_CURRENCY,
LAST_BASE_PAY_INCREASE_US,
LAST_BASE_PAY_INCREASE_DT,
LAST_BASE_PAY_INCREASE_PERCENT,
ONE_TIME_PAYMENT_DT,
LTIP_PLAN_AMT,
LTIP_PLAN_CURRENCY,
EMPLOYEE_TYPE,
END_EMPLOYMENT_DT,
CONTINGENT_WORKER,
CONTINGENT_WORKER_TYPE,
UNION_LOCAL_CODE,
UNION_LOCAL_NAME,
REGION,
WORK_CITY,
WORK_STATE,
WORK_POSTAL_CODE,
WORK_COUNTRY,
DEPT_ID,
COST_CENTER,
COST_CENTER_NAME,
COST_PROFIT_CENTER,
COST_PROFIT_CENTER_ID,
COST_ELEMENT_SUPERIOR,
GENDER,
AGE,
HISPANIC_LATINO,
RACE_ETHNICITY,
VETARAN,
DISBAILITY,
TERMINATION_DT,
TERMINATION_DT_ALL,
TERMINATION_PRIMARY,
WORK_LOCATION,
IS_VOLUNTARY_FG,
BUSINESS_PARTNER,
GENERATION,
PAY_COMPANY,
BASE_PAY_RANGE_SEGMENT,
EMAIL,
ACTIVE_STATUS,
ON_LEAVE,
JOB_DESCRIPTION,
SALARY_PLAN,
COMPENSATION_GRADE,
SOURCE_FILENAME
)
select 
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37,
    $38,
    $39,
    $40,
    $41,
    $42,
    $43,
    $44,
    $45,
    $46,
    $47,
    $48,
    $49,
    $50,
    $51,
    $52,
    $53,
    $54,
    $55,
    $56,
    $57,
    $58,
    $59,
    $60,
    $61,
    $62,
    $63,
    $64,
    $65,
    $66,
    $67,
    $68,
    $69,
    $70,
    $71,
    $72,
    $73,
    $74,
    $75,
    $76,
    $77,
    $78,
    $79,
    $80,
    $81,
    $82,
    $83,
    $84,
    $85,
    $86,
    $87,
    $88,
    $89,
    $90,
    $91,
    $92,
    $93,
    $94,
    $95,
    $96,
    $97,
    $98,
    $99,
    $100,
    $101,
    $102,
    $103,
    $104,
    $105,
    $106,
    $107,
    $108,
    $109,
    $110,
    METADATA$FILENAME
from @PO_STAGE_DB.PUBLIC.MY_S3_STAGE/WD_Snapshot_'|| Filedate ||'_hashed.csv (file_format => PO_STAGE_DB."Worker".csv_load_format ) t
'

;

execute immediate :ins_statement;

SELECT max(Snapshot_Dt) INTO max_date_stg FROM PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage;

SELECT max(Snapshot_Dt) INTO max_date FROM PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage;

IF (max_date_stg >= max_date) then

Delete from PO_HRIS_DB."Worker".PO_Worker_Snapshot 
Where SNAPSHOT_DT IN ( Select case when Max(SNAPSHOT_DT) = last_day(max(SNAPSHOT_DT)) then null else Max(SNAPSHOT_DT) end from PO_HRIS_DB."Worker".PO_Worker_Snapshot);

 

INSERT INTO PO_HRIS_DB."Worker".PO_Worker_Snapshot
(
 Snapshot_Dt  ,
Employee_ID  ,
Workday_ID  ,
Candidate_ID  ,
Candidate  ,
Business_Unit  ,
Division  ,
Sub_Division  ,
Dept  ,
Sub_Dept  ,
Line_of_Business  ,
SPE_Business_Unit  ,
SPE_Division  ,
SPE_Sub_Division  ,
SPE_Dept  ,
SPE_Sub_Dept  ,
Benefit_Code  ,
Org_Level  ,
Management_Level  ,
Hire_Dt  ,
Original_Hire_Dt  ,
Continuous_Service_Dt  ,
Time_in_Job  ,
Job_Code  ,
Job_Title  ,
Job_Family_Func  ,
Job_Family_Grp  ,
Job_Family  ,
Business_Title  ,
Exempt  ,
FTE   ,
Time_Type  ,
Pay_Rate_Type  ,
Pay_Frequency  ,
Hourly_Rate  ,
Hourly_Rate_Currency  ,
Annual_Base_Pay  ,
Annual_Base_Currency  ,
Annual_Base_Pay_US  ,
Aspire_Target_Percentage  ,
Aspire_Bonus_Plan  ,
Aspire_Bonus  ,
Aspire_Bonus_Currency  ,
Aspire_Bonus_Plan_US  ,
Supervisory_Org  ,
Hierarchy_L1  ,
Hierarchy_L2  ,
Hierarchy_L3  ,
Hierarchy_L4  ,
Hierarchy_L5  ,
Hierarchy_L6  ,
Hierarchy_L7  ,
Hierarchy_L8  ,
Hierarchy_L9  ,
Hierarchy_L10  ,
Manager_Job_Title  ,
Manager_Work_Email  ,
Manager_Gender  ,
Direct_Reports  ,
Span_of_Control  ,
Last_Base_Pay_Increase  ,
Last_Base_Pay_Increase_Currency  ,
Last_Base_Pay_Increase_US  ,
Last_Base_Pay_Increase_Dt  ,
Last_Base_Pay_Increase_Percent  ,
One_Time_Payment_Dt  ,
LTIP_Plan_Amt  ,
LTIP_Plan_Currency  ,
Employee_Type  ,
End_Employment_Dt  ,
Contingent_Worker  ,
Contingent_Worker_Type  ,
Union_Local_Code  ,
Union_Local_Name  ,
Region  ,
Work_City  ,
Work_State  ,
Work_Postal_Code  ,
Work_Country  ,
Dept_ID  ,
Cost_Center  ,
Cost_Center_Name  ,
Cost_Profit_Center  ,
Cost_Profit_Center_ID  ,
Cost_Element_Superior  ,
Gender  ,
Age  ,
Hispanic_Latino  ,
Race_Ethnicity  ,
Vetaran  ,
Disbaility  ,
Termination_Dt  ,
Work_Location  ,
Is_Voluntary_FG  ,
Business_Partner  ,
Generation  ,
Pay_Company  ,
Base_Pay_Range_Segment  ,
Email  ,
Active_Status  ,
On_Leave  ,
Job_Description  ,
Salary_Plan  ,
Compensation_Grade,
Termination_Dt_all,
Termination_Reason,
Is_Rehire,
SOURCE_FILENAME,
Created_Date ,
Created_By ,
Modified_Date ,
Modifeid_By ,
Batch_ID 
)
SELECT
Snapshot_Dt  ,
Employee_ID  ,
Workday_ID  ,
replace (Candidate_ID,'17ea18adaf471a26e57a5091f0a51eba3d04a6b7d52331171bf33f2ea6ecd5437edf71c62e15b5f1cdbc3252c12ed57e296011f2af8b58631dbacbe166ff0b74'),
Candidate  ,
Business_Unit  ,
Division  ,
Sub_Division  ,
Dept  ,
Sub_Dept  ,
Line_of_Business  ,
SPE_Business_Unit  ,
SPE_Division  ,
SPE_Sub_Division  ,
SPE_Dept  ,
SPE_Sub_Dept  ,
Benefit_Code  ,
Org_Level  ,
Management_Level  ,
Hire_Dt  ,
Original_Hire_Dt  ,
Continuous_Service_Dt  ,
Time_in_Job  ,
Job_Code  ,
Job_Title  ,
Job_Family_Func  ,
Job_Family_Grp  ,
Job_Family  ,
Business_Title  ,
Exempt  ,
FTE   ,
Time_Type  ,
Pay_Rate_Type  ,
Pay_Frequency  ,
Hourly_Rate  ,
Hourly_Rate_Currency  ,
Annual_Base_Pay  ,
Annual_Base_Currency  ,
Annual_Base_Pay_US  ,
Aspire_Target_Percentage  ,
Aspire_Bonus_Plan  ,
Aspire_Bonus  ,
Aspire_Bonus_Currency  ,
Aspire_Bonus_Plan_US  ,
Supervisory_Org  ,
Hierarchy_L1  ,
Hierarchy_L2  ,
Hierarchy_L3  ,
Hierarchy_L4  ,
Hierarchy_L5  ,
Hierarchy_L6  ,
Hierarchy_L7  ,
Hierarchy_L8  ,
Hierarchy_L9  ,
Hierarchy_L10  ,
Manager_Job_Title  ,
Manager_Work_Email  ,
Manager_Gender  ,
Direct_Reports  ,
Span_of_Control  ,
Last_Base_Pay_Increase  ,
Last_Base_Pay_Increase_Currency  ,
Last_Base_Pay_Increase_US  ,
Last_Base_Pay_Increase_Dt  ,
Last_Base_Pay_Increase_Percent  ,
One_Time_Payment_Dt  ,
LTIP_Plan_Amt  ,
LTIP_Plan_Currency  ,
Employee_Type  ,
End_Employment_Dt  ,
Contingent_Worker  ,
Contingent_Worker_Type  ,
Union_Local_Code  ,
Union_Local_Name  ,
Region  ,
Work_City  ,
Work_State  ,
Work_Postal_Code  ,
Work_Country  ,
Dept_ID  ,
Cost_Center  ,
Cost_Center_Name  ,
Cost_Profit_Center  ,
Cost_Profit_Center_ID  ,
Cost_Element_Superior  ,
Gender  ,
Age  ,
Hispanic_Latino  ,
Race_Ethnicity  ,
Vetaran  ,
Disbaility  ,
Termination_Dt  ,
Work_Location  ,
Is_Voluntary_FG  ,
Business_Partner  ,
Generation  ,
Pay_Company  ,
Base_Pay_Range_Segment  ,
Email  ,
Active_Status  ,
On_Leave  ,
Job_Description  ,
Salary_Plan  ,
Compensation_Grade,
Termination_Dt_all,
Termination_Primary,
Is_Rehire,
trim(substr(SOURCE_FILENAME,position('/',SOURCE_FILENAME,1)+1, 60)),
//SOURCE_FILENAME,
       :created_datetime ,
         :created_by ,
         :modified_datetime ,
          :modified_by ,
         :Batch_ID 
FROM PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage ;//where snapshot_dt::date >= '2022-12-31' limit 10;

Return 'Data Processed';

else 

Return 'Stage date is less than max snapshot date';

END IF;

  END;

  
  
  --history
INSERT INTO PO_HRIS_DB."Worker".PO_Worker_Snapshot
(
 Snapshot_Dt  ,
Employee_ID  ,
Workday_ID  ,
Candidate_ID  ,
Candidate  ,
//Candidate_IDv2  ,
Business_Unit  ,
Division  ,
Sub_Division  ,
Dept  ,
Sub_Dept  ,
Line_of_Business  ,
SPE_Business_Unit  ,
SPE_Division  ,
SPE_Sub_Division  ,
SPE_Dept  ,
SPE_Sub_Dept  ,
Benefit_Code  ,
Org_Level  ,
Management_Level  ,
Hire_Dt  ,
Original_Hire_Dt  ,
Continuous_Service_Dt  ,
Time_in_Job  ,
Job_Code  ,
Job_Title  ,
Job_Family_Func  ,
Job_Family_Grp  ,
Job_Family  ,
Business_Title  ,
Exempt  ,
FTE   ,
Time_Type  ,
Pay_Rate_Type  ,
Pay_Frequency  ,
Hourly_Rate  ,
Hourly_Rate_Currency  ,
Annual_Base_Pay  ,
Annual_Base_Currency  ,
Annual_Base_Pay_US  ,
Aspire_Target_Percentage  ,
Aspire_Bonus_Plan  ,
Aspire_Bonus  ,
Aspire_Bonus_Currency  ,
Aspire_Bonus_Plan_US  ,
Supervisory_Org  ,
Hierarchy_L1  ,
Hierarchy_L2  ,
Hierarchy_L3  ,
Hierarchy_L4  ,
Hierarchy_L5  ,
Hierarchy_L6  ,
Hierarchy_L7  ,
Hierarchy_L8  ,
Hierarchy_L9  ,
Hierarchy_L10  ,
Manager_Job_Title  ,
Manager_Work_Email  ,
Manager_Gender  ,
Direct_Reports  ,
Span_of_Control  ,
Last_Base_Pay_Increase  ,
Last_Base_Pay_Increase_Currency  ,
Last_Base_Pay_Increase_US  ,
Last_Base_Pay_Increase_Dt  ,
Last_Base_Pay_Increase_Percent  ,
One_Time_Payment_Dt  ,
LTIP_Plan_Amt  ,
LTIP_Plan_Currency  ,
Employee_Type  ,
End_Employment_Dt  ,
Contingent_Worker  ,
Contingent_Worker_Type  ,
Union_Local_Code  ,
Union_Local_Name  ,
Region  ,
Work_City  ,
Work_State  ,
Work_Postal_Code  ,
Work_Country  ,
Dept_ID  ,
Cost_Center  ,
Cost_Center_Name  ,
Cost_Profit_Center  ,
Cost_Profit_Center_ID  ,
Cost_Element_Superior  ,
Gender  ,
Age  ,
Hispanic_Latino  ,
Race_Ethnicity  ,
Vetaran  ,
Disbaility  ,
Termination_Dt  ,
Work_Location  ,
Is_Voluntary_FG  ,
Business_Partner  ,
Generation  ,
Pay_Company  ,
Base_Pay_Range_Segment  ,
Email  ,
Active_Status  ,
On_Leave  ,
Job_Description  ,
Salary_Plan  ,
Compensation_Grade,
Termination_Dt_all,
//Termination_Reason,
Is_Rehire,
SOURCE_FILENAME,
Created_Date ,
Created_By ,
Modified_Date ,
Modifeid_By ,
Batch_ID 
)
select
 Snapshot_Dt  ,
Employee_ID  ,
Workday_ID  ,
Candidate_ID  ,
Candidate  ,
//Candidate_IDv2  ,
Business_Unit  ,
Division  ,
Sub_Division  ,
Dept  ,
Sub_Dept  ,
Line_of_Business  ,
SPE_Business_Unit  ,
SPE_Division  ,
SPE_Sub_Division  ,
SPE_Dept  ,
SPE_Sub_Dept  ,
Benefit_Code  ,
Org_Level  ,
Management_Level  ,
Hire_Dt  ,
Original_Hire_Dt  ,
Continuous_Service_Dt  ,
Time_in_Job  ,
Job_Code  ,
Job_Title  ,
Job_Family_Func  ,
Job_Family_Grp  ,
Job_Family  ,
Business_Title  ,
Exempt  ,
FTE   ,
Time_Type  ,
Pay_Rate_Type  ,
Pay_Frequency  ,
Hourly_Rate  ,
Hourly_Rate_Currency  ,
Annual_Base_Pay  ,
Annual_Base_Currency  ,
Annual_Base_Pay_US  ,
Aspire_Target_Percentage  ,
Aspire_Bonus_Plan  ,
Aspire_Bonus  ,
Aspire_Bonus_Currency  ,
Aspire_Bonus_Plan_US  ,
Supervisory_Org  ,
Hierarchy_L1  ,
Hierarchy_L2  ,
Hierarchy_L3  ,
Hierarchy_L4  ,
Hierarchy_L5  ,
Hierarchy_L6  ,
Hierarchy_L7  ,
Hierarchy_L8  ,
Hierarchy_L9  ,
Hierarchy_L10  ,
Manager_Job_Title  ,
Manager_Work_Email  ,
Manager_Gender  ,
Direct_Reports  ,
Span_of_Control  ,
Last_Base_Pay_Increase  ,
Last_Base_Pay_Increase_Currency  ,
Last_Base_Pay_Increase_US  ,
Last_Base_Pay_Increase_Dt  ,
Last_Base_Pay_Increase_Percent  ,
One_Time_Payment_Dt  ,
LTIP_Plan_Amt  ,
LTIP_Plan_Currency  ,
Employee_Type  ,
End_Employment_Dt  ,
Contingent_Worker  ,
Contingent_Worker_Type  ,
Union_Local_Code  ,
Union_Local_Name  ,
Region  ,
Work_City  ,
Work_State  ,
Work_Postal_Code  ,
Work_Country  ,
Dept_ID  ,
Cost_Center  ,
Cost_Center_Name  ,
Cost_Profit_Center  ,
Cost_Profit_Center_ID  ,
Cost_Element_Superior  ,
Gender  ,
Age  ,
Hispanic_Latino  ,
Race_Ethnicity  ,
Vetaran  ,
Disbaility  ,
Termination_Dt  ,
Work_Location  ,
Is_Voluntary_FG  ,
Business_Partner  ,
Generation  ,
Pay_Company  ,
Base_Pay_Range_Segment  ,
Email  ,
Active_Status  ,
On_Leave  ,
Job_Description  ,
Salary_Plan  ,
Compensation_Grade,
Termination_Dt_all,
//Termination_Reason,
Is_Rehire,
SOURCE_FILENAME,
Created_Date ,
Created_By ,
Modified_Date ,
Modifeid_By ,
Batch_ID from PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203;

--latest
CREATE OR REPLACE PROCEDURE PO_HRIS_DB."Worker".SP_WD_SNAPSHOT_LOAD("FILEDATE" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
  
declare
record_date date;
created_datetime timestamp;
modified_datetime timestamp;
created_by string;
modified_by string;
max_date_stg date;
max_date date;
batch_id int;

begin


record_date := current_date();
created_datetime := current_timestamp(); 
modified_datetime := current_timestamp(); 
created_by := current_user();
modified_by :=  current_user();
select ((to_char(current_date -1,''YYYYMMDD'') )::int) into batch_id;

truncate table PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage;

let ins_statement:= 
''
INSERT INTO PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage
(
	SNAPSHOT_DT,
EMPLOYEE_ID,
WORKDAY_ID,
CANDIDATE_ID,
CANDIDATE,
CANDIDATE_IDV2,
BUSINESS_UNIT,
DIVISION,
SUB_DIVISION,
DEPT,
SUB_DEPT,
LINE_OF_BUSINESS,
SPE_BUSINESS_UNIT,
SPE_DIVISION,
SPE_SUB_DIVISION,
SPE_DEPT,
SPE_SUB_DEPT,
BENEFIT_CODE,
ORG_LEVEL,
MANAGEMENT_LEVEL,
HIRE_DT,
ORIGINAL_HIRE_DT,
IS_REHIRE,
CONTINUOUS_SERVICE_DT,
TIME_IN_JOB,
JOB_CODE,
JOB_TITLE,
JOB_FAMILY_FUNC,
JOB_FAMILY_GRP,
JOB_FAMILY,
BUSINESS_TITLE,
EXEMPT,
FTE,
TIME_TYPE,
PAY_RATE_TYPE,
PAY_FREQUENCY,
HOURLY_RATE,
HOURLY_RATE_CURRENCY,
ANNUAL_BASE_PAY,
ANNUAL_BASE_CURRENCY,
ANNUAL_BASE_PAY_US,
ANNUAL_BASE_CURRENCY_US,
ASPIRE_TARGET_PERCENTAGE,
ASPIRE_BONUS_PLAN,
ASPIRE_BONUS,
ASPIRE_BONUS_CURRENCY,
ASPIRE_BONUS_PLAN_US,
CURRENCY1,
SUPERVISORY_ORG,
HIERARCHY_L1,
HIERARCHY_L2,
HIERARCHY_L3,
HIERARCHY_L4,
HIERARCHY_L5,
HIERARCHY_L6,
HIERARCHY_L7,
HIERARCHY_L8,
HIERARCHY_L9,
HIERARCHY_L10,
MANAGER_JOB_TITLE,
MANAGER_WORK_EMAIL,
MANAGER_GENDER,
DIRECT_REPORTS,
SPAN_OF_CONTROL,
LAST_BASE_PAY_INCREASE,
LAST_BASE_PAY_INCREASE_CURRENCY,
LAST_BASE_PAY_INCREASE_US,
LAST_BASE_PAY_INCREASE_DT,
LAST_BASE_PAY_INCREASE_PERCENT,
ONE_TIME_PAYMENT_DT,
LTIP_PLAN_AMT,
LTIP_PLAN_CURRENCY,
EMPLOYEE_TYPE,
END_EMPLOYMENT_DT,
CONTINGENT_WORKER,
CONTINGENT_WORKER_TYPE,
UNION_LOCAL_CODE,
UNION_LOCAL_NAME,
REGION,
WORK_CITY,
WORK_STATE,
WORK_POSTAL_CODE,
WORK_COUNTRY,
DEPT_ID,
COST_CENTER,
COST_CENTER_NAME,
COST_PROFIT_CENTER,
COST_PROFIT_CENTER_ID,
COST_ELEMENT_SUPERIOR,
GENDER,
AGE,
HISPANIC_LATINO,
RACE_ETHNICITY,
VETARAN,
DISBAILITY,
TERMINATION_DT,
TERMINATION_DT_ALL,
TERMINATION_PRIMARY,
WORK_LOCATION,
IS_VOLUNTARY_FG,
BUSINESS_PARTNER,
GENERATION,
PAY_COMPANY,
BASE_PAY_RANGE_SEGMENT,
EMAIL,
ACTIVE_STATUS,
ON_LEAVE,
JOB_DESCRIPTION,
SALARY_PLAN,
COMPENSATION_GRADE,
SOURCE_FILENAME
)
select 
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37,
    $38,
    $39,
    $40,
    $41,
    $42,
    $43,
    $44,
    $45,
    $46,
    $47,
    $48,
    $49,
    $50,
    $51,
    $52,
    $53,
    $54,
    $55,
    $56,
    $57,
    $58,
    $59,
    $60,
    $61,
    $62,
    $63,
    $64,
    $65,
    $66,
    $67,
    $68,
    $69,
    $70,
    $71,
    $72,
    $73,
    $74,
    $75,
    $76,
    $77,
    $78,
    $79,
    $80,
    $81,
    $82,
    $83,
    $84,
    $85,
    $86,
    $87,
    $88,
    $89,
    $90,
    $91,
    $92,
    $93,
    $94,
    $95,
    $96,
    $97,
    $98,
    $99,
    $100,
    $101,
    $102,
    $103,
    $104,
    $105,
    $106,
    $107,
    $108,
    $109,
    $110,
    METADATA$FILENAME
from @PO_STAGE_DB.PUBLIC.MY_S3_STAGE/WD_Snapshot_''|| Filedate ||''_hashed.csv (file_format => PO_STAGE_DB."Worker".csv_load_format ) t
''

;

execute immediate :ins_statement;

SELECT max(Snapshot_Dt) INTO max_date_stg FROM PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage;

SELECT max(Snapshot_Dt) INTO max_date FROM PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage;

IF (max_date_stg >= max_date) then

Delete from PO_HRIS_DB."Worker".PO_Worker_Snapshot 
Where SNAPSHOT_DT IN ( Select case when Max(SNAPSHOT_DT) = last_day(max(SNAPSHOT_DT)) then null else Max(SNAPSHOT_DT) end from PO_HRIS_DB."Worker".PO_Worker_Snapshot);

 

INSERT INTO PO_HRIS_DB."Worker".PO_Worker_Snapshot
(
 Snapshot_Dt  ,
Employee_ID  ,
Workday_ID  ,
Candidate_ID  ,
Candidate  ,
Business_Unit  ,
Division  ,
Sub_Division  ,
Dept  ,
Sub_Dept  ,
Line_of_Business  ,
SPE_Business_Unit  ,
SPE_Division  ,
SPE_Sub_Division  ,
SPE_Dept  ,
SPE_Sub_Dept  ,
Benefit_Code  ,
Org_Level  ,
Management_Level  ,
Hire_Dt  ,
Original_Hire_Dt  ,
Continuous_Service_Dt  ,
Time_in_Job  ,
Job_Code  ,
Job_Title  ,
Job_Family_Func  ,
Job_Family_Grp  ,
Job_Family  ,
Business_Title  ,
Exempt  ,
FTE   ,
Time_Type  ,
Pay_Rate_Type  ,
Pay_Frequency  ,
Hourly_Rate  ,
Hourly_Rate_Currency  ,
Annual_Base_Pay  ,
Annual_Base_Currency  ,
Annual_Base_Pay_US  ,
Aspire_Target_Percentage  ,
Aspire_Bonus_Plan  ,
Aspire_Bonus  ,
Aspire_Bonus_Currency  ,
Aspire_Bonus_Plan_US  ,
Supervisory_Org  ,
Hierarchy_L1  ,
Hierarchy_L2  ,
Hierarchy_L3  ,
Hierarchy_L4  ,
Hierarchy_L5  ,
Hierarchy_L6  ,
Hierarchy_L7  ,
Hierarchy_L8  ,
Hierarchy_L9  ,
Hierarchy_L10  ,
Manager_Job_Title  ,
Manager_Work_Email  ,
Manager_Gender  ,
Direct_Reports  ,
Span_of_Control  ,
Last_Base_Pay_Increase  ,
Last_Base_Pay_Increase_Currency  ,
Last_Base_Pay_Increase_US  ,
Last_Base_Pay_Increase_Dt  ,
Last_Base_Pay_Increase_Percent  ,
One_Time_Payment_Dt  ,
LTIP_Plan_Amt  ,
LTIP_Plan_Currency  ,
Employee_Type  ,
End_Employment_Dt  ,
Contingent_Worker  ,
Contingent_Worker_Type  ,
Union_Local_Code  ,
Union_Local_Name  ,
Region  ,
Work_City  ,
Work_State  ,
Work_Postal_Code  ,
Work_Country  ,
Dept_ID  ,
Cost_Center  ,
Cost_Center_Name  ,
Cost_Profit_Center  ,
Cost_Profit_Center_ID  ,
Cost_Element_Superior  ,
Gender  ,
Age  ,
Hispanic_Latino  ,
Race_Ethnicity  ,
Vetaran  ,
Disbaility  ,
Termination_Dt  ,
Work_Location  ,
Is_Voluntary_FG  ,
Business_Partner  ,
Generation  ,
Pay_Company  ,
Base_Pay_Range_Segment  ,
Email  ,
Active_Status  ,
On_Leave  ,
Job_Description  ,
Salary_Plan  ,
Compensation_Grade,
Termination_Dt_all,
Termination_Reason,
Is_Rehire,
SOURCE_FILENAME,
Created_Date ,
Created_By ,
Modified_Date ,
Modifeid_By ,
Batch_ID 
)
SELECT
Snapshot_Dt  ,
Employee_ID  ,
Workday_ID  ,
replace (Candidate_ID,''17ea18adaf471a26e57a5091f0a51eba3d04a6b7d52331171bf33f2ea6ecd5437edf71c62e15b5f1cdbc3252c12ed57e296011f2af8b58631dbacbe166ff0b74''),
Candidate  ,
Business_Unit  ,
Division  ,
Sub_Division  ,
Dept  ,
Sub_Dept  ,
Line_of_Business  ,
SPE_Business_Unit  ,
SPE_Division  ,
SPE_Sub_Division  ,
SPE_Dept  ,
SPE_Sub_Dept  ,
Benefit_Code  ,
Org_Level  ,
Management_Level  ,
Hire_Dt  ,
Original_Hire_Dt  ,
Continuous_Service_Dt  ,
Time_in_Job  ,
Job_Code  ,
Job_Title  ,
Job_Family_Func  ,
Job_Family_Grp  ,
Job_Family  ,
Business_Title  ,
Exempt  ,
FTE   ,
Time_Type  ,
Pay_Rate_Type  ,
Pay_Frequency  ,
Hourly_Rate  ,
Hourly_Rate_Currency  ,
Annual_Base_Pay  ,
Annual_Base_Currency  ,
Annual_Base_Pay_US  ,
Aspire_Target_Percentage  ,
Aspire_Bonus_Plan  ,
Aspire_Bonus  ,
Aspire_Bonus_Currency  ,
Aspire_Bonus_Plan_US  ,
Supervisory_Org  ,
Hierarchy_L1  ,
Hierarchy_L2  ,
Hierarchy_L3  ,
Hierarchy_L4  ,
Hierarchy_L5  ,
Hierarchy_L6  ,
Hierarchy_L7  ,
Hierarchy_L8  ,
Hierarchy_L9  ,
Hierarchy_L10  ,
Manager_Job_Title  ,
Manager_Work_Email  ,
Manager_Gender  ,
Direct_Reports  ,
Span_of_Control  ,
Last_Base_Pay_Increase  ,
Last_Base_Pay_Increase_Currency  ,
Last_Base_Pay_Increase_US  ,
Last_Base_Pay_Increase_Dt  ,
Last_Base_Pay_Increase_Percent  ,
One_Time_Payment_Dt  ,
LTIP_Plan_Amt  ,
LTIP_Plan_Currency  ,
Employee_Type  ,
End_Employment_Dt  ,
Contingent_Worker  ,
Contingent_Worker_Type  ,
Union_Local_Code  ,
Union_Local_Name  ,
Region  ,
Work_City  ,
Work_State  ,
Work_Postal_Code  ,
Work_Country  ,
Dept_ID  ,
Cost_Center  ,
Cost_Center_Name  ,
Cost_Profit_Center  ,
Cost_Profit_Center_ID  ,
Cost_Element_Superior  ,
Gender  ,
Age  ,
Hispanic_Latino  ,
Race_Ethnicity  ,
Vetaran  ,
Disbaility  ,
Termination_Dt  ,
Work_Location  ,
Is_Voluntary_FG  ,
Business_Partner  ,
Generation  ,
Pay_Company  ,
Base_Pay_Range_Segment  ,
Email  ,
Active_Status  ,
On_Leave  ,
Job_Description  ,
Salary_Plan  ,
Compensation_Grade,
Termination_Dt_all,
Termination_Primary,
Is_Rehire,
trim(substr(SOURCE_FILENAME,position(''/'',SOURCE_FILENAME,1)+1, 60)),
//SOURCE_FILENAME,
       :created_datetime ,
         :created_by ,
         :modified_datetime ,
          :modified_by ,
         :Batch_ID 
FROM PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage ;

Delete from TABLEAU.PUBLIC.WD_WORKER_SNAPSHOT
Where SNAPSHOT_DT IN ( Select case when Max(SNAPSHOT_DT) = last_day(max(SNAPSHOT_DT)) then null else Max(SNAPSHOT_DT) end from TABLEAU.PUBLIC.WD_WORKER_SNAPSHOT);


INSERT INTO TABLEAU.PUBLIC.WD_WORKER_SNAPSHOT
(
SNAPSHOT_DT,
EMPLOYEE_ID,
WORKDAY_ID,
CANDIDATE_ID,
SPE_BUSINESS_UNIT,
SPE_DIVISION,
SPE_SUB_DIVISION,
SPE_DEPT,
SPE_SUB_DEPT,
BENEFIT_CODE,
ORG_LEVEL,
MANAGEMENT_LEVEL,
HIRE_DT,
ORIGINAL_HIRE_DT,
CONTINUOUS_SERVICE_DT,
TENURE_MONTHS,
JOB_CODE,
JOB_TITLE,
JOB_FAMILY_FUNC,
JOB_FAMILY_GRP,
JOB_FAMILY,
BUSINESS_TITLE,
EXEMPT,
FTE,
TIME_TYPE,
PAY_RATE_TYPE,
PAY_FREQUENCY,
HOURLY_RATE,
HOURLY_RATE_CURRENCY,
ANNUAL_BASE_PAY,
ANNUAL_BASE_CURRENCY,
ANNUAL_BASE_PAY_US,
ASPIRE_TARGET_PERCENTAGE,
ASPIRE_BONUS_PLAN,
ASPIRE_BONUS,
ASPIRE_BONUS_CURRENCY,
ASPIRE_BONUS_PLAN_US,
SUPERVISORY_ORG,
HIERARCHY_1,
HIERARCHY_2,
HIERARCHY_3,
HIERARCHY_4,
HIERARCHY_5,
HIERARCHY_6,
HIERARCHY_7,
HIERARCHY_8,
HIERARCHY_9,
HIERARCHY_10,
MANAGER_JOB_TITLE,
MANAGER_WORK_EMAIL,
MANAGER_GENDER,
DIRECT_REPORTS,
SPAN_OF_CONTROL,
LAST_BASE_PAY_INCREASE,
LAST_BASE_PAY_INCREASE_CURRENCY,
LAST_BASE_PAY_INCREASE_US,
LAST_BASE_PAY_INCREASE_DT,
LAST_BASE_PAY_INCREASE_PERCENT,
ONE_TIME_PAYMENT_DT,
LTIP_PLAN_AMT,
LTIP_PLAN_CURRENCY,
EMPLOYEE_TYPE,
END_EMPLOYMENT_DT,
CONTINGENT_WORKER,
CONTINGENT_WORKER_TYPE,
UNION_LOCAL_CODE,
UNION_LOCAL_NAME,
REGION,
WORK_CITY,
WORK_STATE,
WORK_POSTAL_CODE,
WORK_COUNTRY,
DEPT_ID,
COST_CENTER,
COST_CENTER_NAME,
COST_PROFIT_CENTER,
COST_PROFIT_CENTER_ID,
COST_ELEMENT_SUPERIOR,
GENDER,
AGE,
HISPANIC_LATINO,
RACE_ETHNICITY,
VETARAN,
DISBAILITY,
TERMINATION_DT,
WORK_LOCATION,
IS_VOLUNTARY_FG,
BUSINESS_PARTNER,
GENERATION,
PAY_COMPANY,
BASE_PAY_RANGE_SEGMENT,
EMAIL,
ACTIVE_STATUS,
ON_LEAVE,
JOB_DESCRIPTION,
SALARY_PLAN,
COMPENSATION_GRADE,
TERMINATION_DT_ALL,
TERMINATION_REASON,
IS_REHIRE,
FY_QUARTER,
FISCAL_YEAR,
CORE_HC,
ALL_HC
)
select
Snapshot_Dt  ,
a.Employee_ID  ,
Workday_ID  ,
Candidate_ID  ,
SPE_Business_Unit  ,
SPE_Division  ,
SPE_Sub_Division  ,
SPE_Dept  ,
SPE_Sub_Dept  ,
Benefit_Code,
REGEXP_SUBSTR(Org_Level, ''^[^ ]+'', 1, 1, ''e'') as  Org_Level ,
Management_Level,
Hire_Dt  ,
Original_Hire_Dt  ,
Continuous_Service_Dt  ,
round(months_between(SNAPSHOT_DT,Hire_Dt)) as Tenure_Months,
Job_Code  ,
Job_Title  ,
Job_Family_Func  ,
Job_Family_Grp  ,
Job_Family  ,
Business_Title  ,
Exempt  ,
FTE   ,
Time_Type  ,
Pay_Rate_Type  ,
Pay_Frequency  ,
Hourly_Rate  ,
Hourly_Rate_Currency  ,
Annual_Base_Pay  ,
Annual_Base_Currency  ,
Annual_Base_Pay_US  ,
Aspire_Target_Percentage  ,
Aspire_Bonus_Plan  ,
Aspire_Bonus  ,
Aspire_Bonus_Currency  ,
Aspire_Bonus_Plan_US  ,
Supervisory_Org  ,
reverse(SPLIT_PART(Hierarchy, '','', 1)) AS Hierarchy_1,
  reverse(SPLIT_PART(Hierarchy, '','', 2)) AS Hierarchy_2 ,
    reverse(SPLIT_PART(Hierarchy, '','', 3)) AS Hierarchy_3,
  reverse(SPLIT_PART(Hierarchy, '','', 4)) AS Hierarchy_4,
  reverse(SPLIT_PART(Hierarchy, '','', 5)) AS Hierarchy_5,
  reverse(SPLIT_PART(Hierarchy, '','', 6)) AS Hierarchy_6,
  reverse(SPLIT_PART(Hierarchy, '','', 7) )AS Hierarchy_7,
  reverse(SPLIT_PART(Hierarchy, '','', 8) )AS Hierarchy_8,
  reverse(SPLIT_PART(Hierarchy, '','', 9) )AS Hierarchy_9,
  reverse(SPLIT_PART(Hierarchy, '','', 10) )AS Hierarchy_10 ,
  Manager_Job_Title  ,
Manager_Work_Email  ,
Manager_Gender  ,
Direct_Reports  ,
Span_of_Control  ,
Last_Base_Pay_Increase  ,
Last_Base_Pay_Increase_Currency  ,
Last_Base_Pay_Increase_US  ,
Last_Base_Pay_Increase_Dt  ,
Last_Base_Pay_Increase_Percent  ,
One_Time_Payment_Dt  ,
LTIP_Plan_Amt  ,
LTIP_Plan_Currency  ,
Employee_Type  ,
End_Employment_Dt  ,
Contingent_Worker  ,
Contingent_Worker_Type  ,
Union_Local_Code  ,
Union_Local_Name  ,
Region  ,
INITCAP(Work_City)  as Work_City ,
Work_State  ,
Work_Postal_Code  ,
Work_Country  ,
Dept_ID  ,
Cost_Center  ,
Cost_Center_Name  ,
Cost_Profit_Center  ,
Cost_Profit_Center_ID  ,
Cost_Element_Superior  ,
Gender  ,
Age  ,
Hispanic_Latino  ,
Race_Ethnicity  ,
Vetaran  ,
Disbaility  ,
Termination_Dt  ,
Work_Location  ,
Is_Voluntary_FG  ,
Business_Partner  ,
Generation  ,
Pay_Company  ,
Base_Pay_Range_Segment  ,
Email  ,
Active_Status  ,
On_Leave  ,
Job_Description  ,
Salary_Plan  ,
Compensation_Grade,
Termination_Dt_all,
ifnull(ifnull(concat(''Terminate Employee > '',business_process_reason_category,'' > '',business_process_reason),l.Termination_Reason),a.Termination_Reason) as Termination_Reason,
Is_Rehire,
fy_quarter,
fiscal_year,
case when (ifnull(benefit_code,''abc'') IN (''A1 Regular Corp FT US/PR'',''B3 Show Hire US'',''C1 Local 174 (SPE Interim Med Benefits) US'',''N4 Publicists/Story Analysis US'',''N6 Local 174 (MPIHP) US'',''VA1 Staff Hire CAN'') or employee_type is not null) Then True else False end as CORE_HC,
case when (ifnull(benefit_code,''abc'') NOT IN (''N7 No Benefits US'',''VN7 No Benefits CAN'') or employee_type is null) Then False else  True end as ALL_HC
  from
(select 
reverse(replace(ifnull(Hierarchy_L1 ,''zzzz'') ||'',''||
ifnull(Hierarchy_L2,''zzzz'')   ||'',''||
ifnull(Hierarchy_L3,''zzzz'')   ||'',''||
ifnull(Hierarchy_L4 ,''zzzz'')  ||'',''||
ifnull(Hierarchy_L5 ,''zzzz'')  ||'',''||
ifnull(Hierarchy_L6 ,''zzzz'')  ||'',''||
ifnull(Hierarchy_L7 ,''zzzz'')  ||'',''||
ifnull(Hierarchy_L8 ,''zzzz'')  ||'',''||
ifnull(Hierarchy_L9 ,''zzzz'')  ||'',''||
ifnull(Hierarchy_L10 ,''zzzz''),'',zzzz'','''' )) as Hierarchy,*
from  PO_HRIS_DB."Calender".DIM_DATE dd 
INNER JOIN PO_HRIS_DB."Worker".PO_Worker_Snapshot ss on dd.date = ss.snapshot_dt
where snapshot_dt = (select max(snapshot_dt) from PO_HRIS_DB."Worker".PO_Worker_Snapshot )
)a
left join PO_HRIS_DB."Worker".WORKER_TRANSACTION_TYPE  wt on wt.employee_id = a.employee_id and upper(wt.BUSINESS_PROCESS_TYPE) like ''%TERMINATION%'' and effective_dt between ''2023-01-01'' and ''2024-04-14'' 
and upper(wt.source) = ''LEGACY ACTIVITY'' and a.active_status = ''False''
left join (select employee_id,b.termination_reason from PO_STAGE_DB."Worker".PO_WORKER_SNAPSHOT_20231203 b where snapshot_dt = ''2023-10-31'') l on l.employee_id = a.employee_id // where a.Termination_Reason is not null
;

Return ''Data Processed'';

else 

Return ''Stage date is less than max snapshot date'';

END IF;

  END;
  ';



 