
/*
Notes
Line of business remove
Remove EMployee ID nulls.
Candidate ID populated for 2.8k active employees only
Business Unit Unfilled Tony Ken, what is Tom Rothman?
SPlit Management Level
group name or sub group name?
distro email
Job family and family group
Division is wrong for 709965
Saikat change the date to Month beginning instead of end
*/


CREATE OR REPLACE table PO_Worker_Snapshot_Stage(
Snapshot_Dt Varchar ,
Employee_ID Varchar ,
Workday_ID Varchar ,
Candidate_ID Varchar ,
Candidate Varchar ,
Candidate_IDv2 Varchar ,
Business_Unit Varchar ,
Division Varchar ,
Sub_Division Varchar ,
Dept Varchar ,
Sub_Dept Varchar ,
Line_of_Business Varchar ,
SPE_Business_Unit Varchar ,
SPE_Division Varchar ,
SPE_Sub_Division Varchar ,
SPE_Dept Varchar ,
SPE_Sub_Dept Varchar ,
Benefit_Code Varchar ,
Org_Level Varchar ,
Management_Level Varchar ,
Hire_Dt Varchar ,
Original_Hire_Dt Varchar ,
Continuous_Service_Dt Varchar ,
Time_in_Job Varchar ,
Job_Code Varchar ,
Job_Title Varchar ,
Job_Family_Func Varchar ,
Job_Family_Grp Varchar ,
Job_Family Varchar ,
Business_Title Varchar ,
Exempt Varchar ,
FTE  Varchar ,
Time_Type Varchar ,
Pay_Rate_Type Varchar ,
Pay_Frequency Varchar ,
Hourly_Rate Varchar ,
Hourly_Rate_Currency Varchar ,
Annual_Base_Pay Varchar ,
Annual_Base_Currency Varchar ,
Annual_Base_Pay_US Varchar ,
Annual_Base_Currency_US Varchar ,
Aspire_Target_Percentage Varchar ,
Aspire_Bonus_Plan Varchar ,
Aspire_Bonus Varchar ,
Aspire_Bonus_Currency Varchar ,
Aspire_Bonus_Plan_US Varchar ,
Currency1 Varchar ,
Supervisory_Org Varchar ,
Hierarchy_L1 Varchar ,
Hierarchy_L2 Varchar ,
Hierarchy_L3 Varchar ,
Hierarchy_L4 Varchar ,
Hierarchy_L5 Varchar ,
Hierarchy_L6 Varchar ,
Hierarchy_L7 Varchar ,
Hierarchy_L8 Varchar ,
Hierarchy_L9 Varchar ,
Hierarchy_L10 Varchar ,
Manager_Job_Title Varchar ,
Manager_Work_Email Varchar ,
Manager_Gender Varchar ,
Direct_Reports Varchar ,
Span_of_Control Varchar ,
Last_Base_Pay_Increase Varchar ,
Last_Base_Pay_Increase_Currency Varchar ,
Last_Base_Pay_Increase_US Varchar ,
//Currency2 Varchar ,
Last_Base_Pay_Increase_Dt Varchar ,
Last_Base_Pay_Increase_Percent Varchar ,
One_Time_Payment_Dt Varchar ,
LTIP_Plan_Amt Varchar ,
LTIP_Plan_Currency Varchar ,
Employee_Type Varchar ,
End_Employment_Dt Varchar ,
Contingent_Worker Varchar ,
Contingent_Worker_Type Varchar ,
Union_Local_Code Varchar ,
Union_Local_Name Varchar ,
Region Varchar ,
Work_City Varchar ,
Work_State Varchar ,
Work_Postal_Code Varchar ,
Work_Country Varchar ,
Dept_ID Varchar ,
Cost_Center Varchar ,
Cost_Center_Name Varchar ,
Cost_Profit_Center Varchar ,
Cost_Profit_Center_ID Varchar ,
Cost_Element_Superior Varchar ,
Gender Varchar ,
Age Varchar ,
Hispanic_Latino Varchar ,
Race_Ethnicity Varchar ,
Vetaran Varchar ,
Disbaility Varchar ,
Termination_Dt Varchar ,
Work_Location Varchar ,
Is_Voluntary_FG Varchar ,
Business_Partner Varchar ,
Generation Varchar ,
Pay_Company Varchar ,
Base_Pay_Range_Segment Varchar ,
Email Varchar ,
Active_Status Varchar ,
On_Leave Varchar ,
Job_Description Varchar ,
Salary_Plan Varchar ,
Compensation_Grade Varchar ,
Filename Varchar

);


copy into PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage
from (select 
$1,
$2,
$3,
$4,
$5,
$6,
$7,
$8,
$9,
$10,
$11,
$12,
$13,
$14,
$15,
$16,
$17,
$18,
$19,
$20,
$21,
$22,
$23,
$24,
$25,
$26,
$27,
$28,
$29,
$30,
$31,
$32,
$33,
$34,
$35,
$36,
$37,
$38,
$39,
$40,
$41,
$42,
$43,
$44,
$45,
$46,
$47,
$48,
$49,
$50,
$51,
$52,
$53,
$54,
$55,
$56,
$57,
$58,
$59,
$60,
$61,
$62,
$63,
$64,
$65,
$66,
$67,
$68,
$69,
$70,
$71,
$72,
$73,
$74,
$75,
$76,
$77,
$78,
$79,
$80,
$81,
$82,
$83,
$84,
$85,
$86,
$87,
$88,
$89,
$90,
$91,
$92,
$93,
$94,
$95,
$96,
$97,
$98,
$99,
$100,
$101,
$102,
$103,
$104,
$105,
$106,
$107,
$108,
METADATA$FILENAME
from @PO_STAGE_DB.PUBLIC.MY_S3_STAGE)
pattern = '.*WD_Snapshot_History_*.*_20231120.*csv'
FILE_FORMAT = (  FORMAT_NAME = 'PO_STAGE_DB."Worker".csv_load_format'  TYPE = CSV ) ;

copy into PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage
from (select 
$1,
$2,
$3,
$4,
$5,
$6,
$7,
$8,
$9,
$10,
$11,
$12,
$13,
$14,
$15,
$16,
$17,
$18,
$19,
$20,
$21,
$22,
$23,
$24,
$25,
$26,
$27,
$28,
$29,
$30,
$31,
$32,
$33,
$34,
$35,
$36,
$37,
$38,
$39,
$40,
$41,
$42,
$43,
$44,
$45,
$46,
$47,
$48,
$49,
$50,
$51,
$52,
$53,
$54,
$55,
$56,
$57,
$58,
$59,
$60,
$61,
$62,
$63,
$64,
$65,
$66,
$67,
$68,
$69,
$70,
$71,
$72,
$73,
$74,
$75,
$76,
$77,
$78,
$79,
$80,
$81,
$82,
$83,
$84,
$85,
$86,
$87,
$88,
$89,
$90,
$91,
$92,
$93,
$94,
$95,
$96,
$97,
$98,
$99,
$100,
$101,
$102,
$103,
$104,
$105,
$106,
$107,
//$108,
METADATA$FILENAME
from @PO_STAGE_DB.PUBLIC.MY_S3_STAGE)
pattern = '.*WD_Snapshot_History_*.*_20231122.*csv'
FILE_FORMAT = (  FORMAT_NAME = 'PO_STAGE_DB."Worker".csv_load_format'  TYPE = CSV ) 
;

--rehire
select * from 
PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where termination_dt is not null 
and active_status = '1' 
and snapshot_dt = '2022-12-31' and hire_dt<>original_hire_dt;// limit 10;

Select email, * from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage 
where employee_id = 'abfe470ef6e8c353ec4a25561ac9d34db2b40b758d98085d1e520af522bef11e09115c7cca583b47fd8c13b7946063e37ea8d986dc7123b058971d65db1f46bf' 
and snapshot_dt = '2020-12-31';

'17ea18adaf471a26e57a5091f0a51eba3d04a6b7d52331171bf33f2ea6ecd5437edf71c62e15b5f1cdbc3252c12ed57e296011f2af8b58631dbacbe166ff0b74';

-- to remove duplicates

select count(*),employee_id,snapshot_dt,email from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage  where 
employee_id <> 'd39b0ed639f65927d0b966bf465c4a1f36c87cab929821a9ca59418927e74f7e80abf70accfe44045a96a5e0bdefd95f1997f28f9a647fd664394383ca36db0d'
and contingent_worker is null
//and email not like '%noemail%'
//snapshot_dt = '2022-12-31' 
group by 2,3,4 having count(*) > 1;

select distinct filename from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage 
where 
termination_dt::date > '2022-10-01' 
limit 10;

select * from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage limit 10 ;where //snapshot_dt::date >= '2020-01-31'
termination_dt IN ('2022-10-01') and snapshot_dt = '2022-12-31'
limit 10;


delete from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage where filename like '%outbound/WD_Snapshot_History_2019-06-30_20231120_hashed.csv%';


17ea18adaf471a26e57a5091f0a51eba3d04a6b7d52331171bf33f2ea6ecd5437edf71c62e15b5f1cdbc3252c12ed57e296011f2af8b58631dbacbe166ff0b74
;
select
max(length(Snapshot_Dt))  ,
max(length(Employee_ID))  ,
max(length(Workday_ID))  ,
max(length(Candidate_ID))  ,
max(length(Candidate))  ,
max(length(Candidate_IDv2))  ,
max(length(Business_Unit))  ,
max(length(Division))  ,
max(length(Sub_Division))  ,
max(length(Dept))  ,
max(length(Sub_Dept))  ,
max(length(Line_of_Business))  ,
max(length(SPE_Business_Unit))  ,
max(length(SPE_Division))  ,
max(length(SPE_Sub_Division))  ,
max(length(SPE_Dept))  ,
max(length(SPE_Sub_Dept))  ,
max(length(Benefit_Code))  ,
max(length(Org_Level))  ,
max(length(Management_Level))  ,
max(length(Hire_Dt))  ,
max(length(Original_Hire_Dt))  ,
max(length(Continuous_Service_Dt))  ,
max(length(Time_in_Job))  ,
max(length(Job_Code))  ,
max(length(Job_Title))  ,
max(length(Job_Family_Func))  ,
max(length(Job_Family_Grp))  ,
max(length(Job_Family))  ,
max(length(Business_Title))  ,
max(length(Exempt))  ,
max(length(FTE ))  ,
max(length(Time_Type))  ,
max(length(Pay_Rate_Type))  ,
max(length(Pay_Frequency))  ,
max(length(Hourly_Rate))  ,
max(length(Hourly_Rate_Currency))  ,
max(length(Annual_Base_Pay))  ,
max(length(Annual_Base_Currency))  ,
max(length(Annual_Base_Pay_US))  ,
max(length(Annual_Base_Currency_US))  ,
max(length(Aspire_Target_Percentage))  ,
max(length(Aspire_Bonus_Plan))  ,
max(length(Aspire_Bonus))  ,
max(length(Aspire_Bonus_Currency))  ,
max(length(Aspire_Bonus_Plan_US))  ,
max(length(Currency1))  ,
max(length(Supervisory_Org))  ,
max(length(Hierarchy_L1))  ,
max(length(Hierarchy_L2))  ,
max(length(Hierarchy_L3))  ,
max(length(Hierarchy_L4))  ,
max(length(Hierarchy_L5))  ,
max(length(Hierarchy_L6))  ,
max(length(Hierarchy_L7))  ,
max(length(Hierarchy_L8))  ,
max(length(Hierarchy_L9))  ,
max(length(Hierarchy_L10))  ,
max(length(Manager_Job_Title))  ,
max(length(Manager_Work_Email))  ,
max(length(Manager_Gender))  ,
max(length(Direct_Reports))  ,
max(length(Span_of_Control))  ,
max(length(Last_Base_Pay_Increase))  ,
max(length(Last_Base_Pay_Increase_Currency))  ,
max(length(Last_Base_Pay_Increase_US))  ,
max(length(Last_Base_Pay_Increase_Dt))  ,
max(length(Last_Base_Pay_Increase_Percent))  ,
max(length(One_Time_Payment_Dt))  ,
max(length(LTIP_Plan_Amt))  ,
max(length(LTIP_Plan_Currency))  ,
max(length(Employee_Type))  ,
max(length(End_Employment_Dt))  ,
max(length(Contingent_Worker))  ,
max(length(Contingent_Worker_Type))  ,
max(length(Union_Local_Code))  ,
max(length(Union_Local_Name))  ,
max(length(Region))  ,
max(length(Work_City))  ,
max(length(Work_State))  ,
max(length(Work_Postal_Code))  ,
max(length(Work_Country))  ,
max(length(Dept_ID))  ,
max(length(Cost_Center))  ,
max(length(Cost_Center_Name))  ,
max(length(Cost_Profit_Center))  ,
max(length(Cost_Profit_Center_ID))  ,
max(length(Cost_Element_Superior))  ,
max(length(Gender))  ,
max(length(Age))  ,
max(length(Hispanic_Latino))  ,
max(length(Race_Ethnicity))  ,
max(length(Vetaran))  ,
max(length(Disbaility))  ,
max(length(Termination_Dt))  ,
max(length(Work_Location))  ,
max(length(Is_Voluntary_FG))  ,
max(length(Business_Partner))  ,
max(length(Generation))  ,
max(length(Pay_Company))  ,
max(length(Base_Pay_Range_Segment))  ,
max(length(Email))  ,
max(length(Active_Status))  ,
max(length(On_Leave))  ,
max(length(Job_Description))  ,
max(length(Salary_Plan))  ,
max(length(Compensation_Grade))  

from PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage ;


CREATE OR REPLACE TABLE PO_STAGE_DB."Worker".PO_Worker_Snapshot_Stage
(
Snapshot_Dt Varchar(10),
Employee_ID Varchar(128),
Workday_ID Varchar(32),
Candidate_ID Varchar(128),
Candidate Varchar(150),
Candidate_IDv2 Varchar(20),
Business_Unit Varchar(40),
Division Varchar(50),
Sub_Division Varchar(60),
Dept Varchar(80),
Sub_Dept Varchar(80),
Line_of_Business Varchar(30),
SPE_Business_Unit Varchar(50),
SPE_Division Varchar(50),
SPE_Sub_Division Varchar(60),
SPE_Dept Varchar(80),
SPE_Sub_Dept Varchar(80),
Benefit_Code Varchar(10),
Org_Level Varchar(10),
Management_Level Varchar(30),
Hire_Dt Varchar(10),
Original_Hire_Dt Varchar(10),
Continuous_Service_Dt Varchar(10),
Time_in_Job Varchar(10),
Job_Code Varchar(30),
Job_Title Varchar(120),
Job_Family_Func Varchar(10),
Job_Family_Grp Varchar(60),
Job_Family Varchar(90),
Business_Title Varchar(130),
Exempt Varchar(10),
FTE  Varchar(10),
Time_Type Varchar(10),
Pay_Rate_Type Varchar(20),
Pay_Frequency Varchar(30),
Hourly_Rate Varchar(10),
Hourly_Rate_Currency Varchar(10),
Annual_Base_Pay Varchar(20),
Annual_Base_Currency Varchar(10),
Annual_Base_Pay_US Varchar(10),
Annual_Base_Currency_US Varchar(10),
Aspire_Target_Percentage Varchar(10),
Aspire_Bonus_Plan Varchar(120),
Aspire_Bonus Varchar(20),
Aspire_Bonus_Currency Varchar(10),
Aspire_Bonus_Plan_US Varchar(10),
Currency1 Varchar(10),
Supervisory_Org Varchar(128),
Hierarchy_L1 Varchar(40),
Hierarchy_L2 Varchar(40),
Hierarchy_L3 Varchar(40),
Hierarchy_L4 Varchar(40),
Hierarchy_L5 Varchar(30),
Hierarchy_L6 Varchar(30),
Hierarchy_L7 Varchar(20),
Hierarchy_L8 Varchar(20),
Hierarchy_L9 Varchar(20),
Hierarchy_L10 Varchar(20),
Manager_Job_Title Varchar(120),
Manager_Work_Email Varchar(128),
Manager_Gender Varchar(10),
Direct_Reports Varchar(10),
Span_of_Control Varchar(10),
Last_Base_Pay_Increase Varchar(20),
Last_Base_Pay_Increase_Currency Varchar(10),
Last_Base_Pay_Increase_US Varchar(20),
Last_Base_Pay_Increase_Dt Varchar(10),
Last_Base_Pay_Increase_Percent Varchar(10),
One_Time_Payment_Dt Varchar(10),
LTIP_Plan_Amt Varchar(10),
LTIP_Plan_Currency Varchar(10),
Employee_Type Varchar(30),
End_Employment_Dt Varchar(10),
Contingent_Worker Varchar(40),
Contingent_Worker_Type Varchar(30),
Union_Local_Code Varchar(10),
Union_Local_Name Varchar(80),
Region Varchar(20),
Work_City Varchar(30),
Work_State Varchar(40),
Work_Postal_Code Varchar(20),
Work_Country Varchar(30),
Dept_ID Varchar(10),
Cost_Center Varchar(60),
Cost_Center_Name Varchar(60),
Cost_Profit_Center Varchar(60),
Cost_Profit_Center_ID Varchar(110),
Cost_Element_Superior Varchar(20),
Gender Varchar(30),
Age Varchar(10),
Hispanic_Latino Varchar(10),
Race_Ethnicity Varchar(100),
Vetaran Varchar(70),
Disbaility Varchar(60),
Termination_Dt Varchar(10),
Work_Location Varchar(60),
Is_Voluntary_FG Varchar(10),
Business_Partner Varchar(30),
Generation Varchar(40),
Pay_Company Varchar(50),
Base_Pay_Range_Segment Varchar(20),
Email Varchar(130),
Active_Status Varchar(10),
On_Leave Varchar(3),
Job_Description Varchar,
Salary_Plan Varchar(90),
Compensation_Grade Varchar(30),
Source_FileName Varchar(200)
)