select count(*),employee_id   from "PO_STAGE_DB"."Worker".PO_WD_Worker_Stage group by 2 having count(*)>1 limit 10; where --business_process_type = 'Create Position' and
workday_id is null;


select distinct Busniess_Process_Type,
Business_Process_Reason_Category,
Business_Process_Reason  from "PO_STAGE_DB"."Worker".PO_WD_Worker_Stage where BUSINESS_PROCESS_REASON_CATEGORY like '%Conversion%'


select 
distinct
Workday_ID,
PreHire_ID,
PreHire_WID,
--Action_Event,
Transaction_Status,
Initiated_Date,
Initiating_Worker_ID,
Effective_Date::Date,
Busniess_Process_Type,
Business_Process_Reason_Category,
Business_Process_Reason,
Business_Unit,
Division,
Sub_Division,
Department,
Sub_Department,
Line_of_Business,
Benefit_Code,
Organization_Level_Code,
Management_Level,
Hire_Date,
Original_Hire_Date,
Continuous_Service_Date,
(Job_Code) as Job_Code,
Job_Title,
Job_Family,
Job_Family_Group,
Business_Title,
Exempt_Status,
FTE,
Time_Type,
Pay_Rate_Type,
Frequency,
Compensation_Grade,
Hourly_Amount,
--Currency,
--Currency_1,
Base_Pay_Range_Segment,
ASPIRE_Target_Percentage,
ASPIRE_Bonus_Plan,
ASPIRE_Bonus_Amount,
--Currency_2,
ASPIRE_Bonus_Amount_US,
--Currency_3,
Last_Increase_Date,
Last_Increase_Amount,
--Currency_4,
Last_Increase_Percent,
Last_Bonus_Date,
LTIP_Bonus_Amount,
--Currency_5,
End_Employment_Date,
Employee_Type,
Contingent_Worker_Type,
SPE_Union_Code,
Union_Local_Name_Long_Name,
Work_Location,
Work_Address_City,
Work_Address_State,
Work_Address_Postal_Code,
Work_Address_Country,
Region,
Cost_Center,
SAP_Company,
Pay_Company,
Gender,
Age,
Hispanic_or_Latino,
Race,
Veteran_Status,
(Supervisory_Organization_Proposed_Name) as Supervisory,
Disability,
Termination_Date,
Primary_Business_Partner,
(Employee_Work_Email) as Employee_Work_Email,
On_Leave,
Active_Status,
Manager,
Manager_Job_Title,
(Manager_Work_Email) as Manager_Work_Email,
Manager_Direct_Reports_Count,
Manager_Span_of_Control
from "PO_STAGE_DB"."Worker".PO_WD_Worker_Stage  where employee_id = 720990;
713952;
--business_process_type = 'Create Position' and Source_filename = 'BPT.csv'; --Busniess_Process_Type = 'Termination' ;
workday_id is null;
720192
260483
711601
162864
281047
;
CREATE OR REPLACE TABLE "PO_STAGE_DB"."Worker".po_wd_worker_stage
(
Employee_ID Varchar(500),
Workday_ID Varchar(500),
PreHire_ID Varchar(500),
PreHire_WID Varchar(500),
Action_Event Varchar(500),
Transaction_Status Varchar(500),
Initiated_Date Varchar(500),
Initiating_Worker_ID Varchar(500),
Effective_Date Varchar(500),
Busniess_Process_Type Varchar(500),
Business_Process_Reason_Category Varchar(500),
Business_Process_Reason Varchar(500),
Worker_Type_Current Varchar(500),
Worker_Type_Current_ID Varchar(500),
Worker_Type_Proposed Varchar(500),
Worker_Type_Proposed_ID Varchar(500),
Company_Current Varchar(500),
Company_Current_ID Varchar(500),
Company_Current_Name Varchar(500),
Company_Proposed Varchar(500),
Company_Proposed_ID Varchar(500),
Company_Proposed_Name Varchar(500),
Pay_Group_Current Varchar(500),
Pay_Group_Current_ID Varchar(500),
Pay_Group_Current_Name Varchar(500),
Pay_Group_Proposed Varchar(500),
Pay_Group_Proposed_ID Varchar(500),
Pay_Group_Proposed_Name Varchar(500),
Cost_Center_Current Varchar(500),
Cost_Center_Current_ID Varchar(500),
Cost_Center_Current_Name Varchar(500),
Cost_Center_Proposed Varchar(500),
Cost_Center_Proposed_ID Varchar(500),
Cost_Center_Proposed_Name Varchar(500),
Location_Current Varchar(500),
Location_Current_ID Varchar(500),
Location_Current_Name Varchar(500),
Location_Proposed Varchar(500),
Location_Proposed_ID Varchar(500),
Location_Proposed_Name Varchar(500),
Job_Profile_Current Varchar(500),
Job_Profile_Proposed Varchar(500),
Job_Profile_Proposed_ID Varchar(500),
Job_Profile_Proposed_Name Varchar(500),
Initiating_Person Varchar(500),
Management_Level_Current Varchar(500),
Management_Level_Current_ID Varchar(500),
Management_Level_Proposed Varchar(500),
Management_Level_Proposed_ID Varchar(500),
Supervisory_Organization_Current Varchar(500),
Supervisory_Organization_Current_ID Varchar(500),
Supervisory_Organization_Current_Name Varchar(500),
Supervisory_Organization_Proposed Varchar(500),
Supervisory_Organization_Proposed_ID Varchar(500),
Supervisory_Organization_Proposed_Name Varchar(500),
Manager_Current Varchar(500),
Manager_Current_ID Varchar(500),
Manager_Current_Name Varchar(500),
Manager_Current_WID Varchar(500),
Manager_Proposed Varchar(500),
Manager_Proposed_ID Varchar(500),
Manager_Proposed_Name Varchar(500),
Manager_Proposed_WID Varchar(500),
Department_Current Varchar(500),
Department_Current_ID Varchar(500),
Department_Current_Name Varchar(500),
Department_Proposed Varchar(500),
Department_Proposed_ID Varchar(500),
Department_Proposed_Name Varchar(500),
Sub_Department_Current Varchar(500),
Sub_Department_Current_ID Varchar(500),
Sub_Department_Current_Name Varchar(500),
Sub_Department_Proposed Varchar(500),
Sub_Department_Proposed_ID Varchar(500),
Sub_Department_Proposed_Name Varchar(500),
Division_Current Varchar(500),
Division_Current_ID Varchar(500),
Division_Current_Name Varchar(500),
Division_Proposed Varchar(500),
Division_Proposed_ID Varchar(500),
Division_Proposed_Name Varchar(500),
Sub_Division_Current Varchar(500),
Sub_Division_Current_ID Varchar(500),
Sub_Division_Current_Name Varchar(500),
Sub_Division_Proposed Varchar(500),
Sub_Division_Proposed_ID Varchar(500),
Sub_Division_Proposed_Name Varchar(500),
Planning_Manager_Current Varchar(500),
Planning_Manager_Current_ID Varchar(500),
Planning_Manager_Current_Name Varchar(500),
Planning_Manager_Proposed Varchar(500),
Planning_Manager_Proposed_ID Varchar(500),
Planning_Manager_Proposed_Name Varchar(500),
Cost_Center_Grouping_Current Varchar(500),
Cost_Center_Grouping_Current_ID Varchar(500),
Cost_Center_Grouping_Current_Name Varchar(500),
Cost_Center_Grouping_Proposed Varchar(500),
Cost_Center_Grouping_Proposed_ID Varchar(500),
Cost_Center_Grouping_Proposed_Name Varchar(500),
SAP_Company_Current Varchar(500),
SAP_Company_Current_ID Varchar(500),
SAP_Company_Current_Name Varchar(500),
SAP_Company_Proposed Varchar(500),
SAP_Company_Proposed_ID Varchar(500),
SAP_Company_Proposed_Name Varchar(500),
Account_Current Varchar(500),
Account_Current_ID Varchar(500),
Account_Current_Name Varchar(500),
Account_Proposed Varchar(500),
Account_Proposed_ID Varchar(500),
Account_Proposed_Name Varchar(500),
Line_of_Business_Current Varchar(500),
Line_of_Business_Current_ID Varchar(500),
Line_of_Business_Current_Name Varchar(500),
Line_of_Business_Proposed Varchar(500),
Line_of_Business_Proposed_ID Varchar(500),
Line_of_Business_Proposed_Name Varchar(500),
Geographic_Group_Current Varchar(500),
Geographic_Group_Current_ID Varchar(500),
Geographic_Group_Current_Name Varchar(500),
Geographic_Group_Proposed Varchar(500),
Geographic_Group_Proposed_ID Varchar(500),
Geographic_Group_Proposed_Name Varchar(500),
Profit_Center_Current Varchar(500),
Profit_Center_Current_ID Varchar(500),
Profit_Center_Current_Name Varchar(500),
Profit_Center_Proposed Varchar(500),
Profit_Center_Proposed_ID Varchar(500),
Profit_Center_Proposed_Name Varchar(500),
Sony_Payroll_Company_Current Varchar(500),
Sony_Payroll_Company_Current_ID Varchar(500),
Sony_Payroll_Company_Current_Name Varchar(500),
Sony_Payroll_Company_Proposed Varchar(500),
Sony_Payroll_Company_Proposed_ID Varchar(500),
Sony_Payroll_Company_Proposed_Name Varchar(500),
Time_Type_Current Varchar(500),
Time_Type_Current_ID Varchar(500),
Time_Type_Proposed Varchar(500),
Time_Type_Proposed_ID Varchar(500),
Pay_Rate_Type_Current Varchar(500),
Pay_Rate_Type_Current_ID Varchar(500),
Pay_Rate_Type_Proposed Varchar(500),
Pay_Rate_Type_Proposed_ID Varchar(500),
Paid_FTE_Current Varchar(500),
Paid_FTE_Proposed Varchar(500),
Job_Exempt_Current Varchar(500),
Job_Exempt_Proposed Varchar(500),
Base_Pay_Current Varchar(500),
Currency_8 Varchar(500),
Base_Pay_Proposed Varchar(500),
Currency_9 Varchar(500),
Hourly_Rate_Current_Amount Varchar(500),
Currency_6 Varchar(500),
Hourly_Rate_Proposed_Amount Varchar(500),
Currency_7 Varchar(500),
--Employee_ID Varchar(500),
Business_Unit Varchar(500),
Division Varchar(500),
Sub_Division Varchar(500),
Department Varchar(500),
Sub_Department Varchar(500),
Line_of_Business Varchar(500),
Benefit_Code Varchar(500),
Organization_Level_Code Varchar(500),
Management_Level Varchar(500),
Hire_Date Varchar(500),
Original_Hire_Date Varchar(500),
Continuous_Service_Date Varchar(500),
Job_Code Varchar(500),
Job_Title Varchar(500),
Job_Family Varchar(500),
Job_Family_Group Varchar(500),
Business_Title Varchar(500),
Exempt_Status Varchar(500),
FTE Varchar(500),
Time_Type Varchar(500),
Pay_Rate_Type Varchar(500),
Frequency Varchar(500),
Compensation_Grade Varchar(500),
Hourly_Amount Varchar(500),
Currency Varchar(500),
Currency_1 Varchar(500),
Base_Pay_Range_Segment Varchar(500),
ASPIRE_Target_Percentage Varchar(500),
ASPIRE_Bonus_Plan Varchar(500),
ASPIRE_Bonus_Amount Varchar(500),
Currency_2 Varchar(500),
ASPIRE_Bonus_Amount_US Varchar(500),
Currency_3 Varchar(500),
Last_Increase_Date Varchar(500),
Last_Increase_Amount Varchar(500),
Currency_4 Varchar(500),
Last_Increase_Percent Varchar(500),
Last_Bonus_Date Varchar(500),
LTIP_Bonus_Amount Varchar(500),
Currency_5 Varchar(500),
End_Employment_Date Varchar(500),
Employee_Type Varchar(500),
Contingent_Worker_Type Varchar(500),
SPE_Union_Code Varchar(500),
Union_Local_Name_Long_Name Varchar(500),
Work_Location Varchar(500),
Work_Address_City Varchar(500),
Work_Address_State Varchar(500),
Work_Address_Postal_Code Varchar(500),
Work_Address_Country Varchar(500),
Region Varchar(500),
Cost_Center Varchar(500),
SAP_Company Varchar(500),
Pay_Company Varchar(500),
Gender Varchar(500),
Age Varchar(500),
Hispanic_or_Latino Varchar(500),
Race Varchar(500),
Veteran_Status Varchar(500),
Disability Varchar(500),
Termination_Date Varchar(500),
Primary_Business_Partner Varchar(500),
Employee_Work_Email Varchar(500),
On_Leave Varchar(500),
Active_Status Varchar(500),
Manager Varchar(500),
Manager_Job_Title Varchar(500),
Manager_Work_Email Varchar(500),
Manager_Direct_Reports_Count Varchar(500),
Manager_Span_of_Control Varchar(500),
Source_Filename Varchar(100)

)
;

INSERT INTO "PO_STAGE_DB"."Worker".PO_WD_Worker_Stage
(
Employee_ID,
Workday_ID,
PreHire_ID,
PreHire_WID,
Action_Event,
Transaction_Status,
Initiated_Date,
Initiating_Worker_ID,
Effective_Date,
Busniess_Process_Type,
Business_Process_Reason_Category,
Business_Process_Reason,
Worker_Type_Current,
Worker_Type_Current_ID,
Worker_Type_Proposed,
Worker_Type_Proposed_ID,
Company_Current,
Company_Current_ID,
Company_Current_Name,
Company_Proposed,
Company_Proposed_ID,
Company_Proposed_Name,
Pay_Group_Current,
Pay_Group_Current_ID,
Pay_Group_Current_Name,
Pay_Group_Proposed,
Pay_Group_Proposed_ID,
Pay_Group_Proposed_Name,
Cost_Center_Current,
Cost_Center_Current_ID,
Cost_Center_Current_Name,
Cost_Center_Proposed,
Cost_Center_Proposed_ID,
Cost_Center_Proposed_Name,
Location_Current,
Location_Current_ID,
Location_Current_Name,
Location_Proposed,
Location_Proposed_ID,
Location_Proposed_Name,
Job_Profile_Current,
Job_Profile_Proposed,
Job_Profile_Proposed_ID,
Job_Profile_Proposed_Name,
Initiating_Person,
Management_Level_Current,
Management_Level_Current_ID,
Management_Level_Proposed,
Management_Level_Proposed_ID,
Supervisory_Organization_Current,
Supervisory_Organization_Current_ID,
Supervisory_Organization_Current_Name,
Supervisory_Organization_Proposed,
Supervisory_Organization_Proposed_ID,
Supervisory_Organization_Proposed_Name,
Manager_Current,
Manager_Current_ID,
Manager_Current_Name,
Manager_Current_WID,
Manager_Proposed,
Manager_Proposed_ID,
Manager_Proposed_Name,
Manager_Proposed_WID,
Department_Current,
Department_Current_ID,
Department_Current_Name,
Department_Proposed,
Department_Proposed_ID,
Department_Proposed_Name,
Sub_Department_Current,
Sub_Department_Current_ID,
Sub_Department_Current_Name,
Sub_Department_Proposed,
Sub_Department_Proposed_ID,
Sub_Department_Proposed_Name,
Division_Current,
Division_Current_ID,
Division_Current_Name,
Division_Proposed,
Division_Proposed_ID,
Division_Proposed_Name,
Sub_Division_Current,
Sub_Division_Current_ID,
Sub_Division_Current_Name,
Sub_Division_Proposed,
Sub_Division_Proposed_ID,
Sub_Division_Proposed_Name,
Planning_Manager_Current,
Planning_Manager_Current_ID,
Planning_Manager_Current_Name,
Planning_Manager_Proposed,
Planning_Manager_Proposed_ID,
Planning_Manager_Proposed_Name,
Cost_Center_Grouping_Current,
Cost_Center_Grouping_Current_ID,
Cost_Center_Grouping_Current_Name,
Cost_Center_Grouping_Proposed,
Cost_Center_Grouping_Proposed_ID,
Cost_Center_Grouping_Proposed_Name,
SAP_Company_Current,
SAP_Company_Current_ID,
SAP_Company_Current_Name,
SAP_Company_Proposed,
SAP_Company_Proposed_ID,
SAP_Company_Proposed_Name,
Account_Current,
Account_Current_ID,
Account_Current_Name,
Account_Proposed,
Account_Proposed_ID,
Account_Proposed_Name,
Line_of_Business_Current,
Line_of_Business_Current_ID,
Line_of_Business_Current_Name,
Line_of_Business_Proposed,
Line_of_Business_Proposed_ID,
Line_of_Business_Proposed_Name,
Geographic_Group_Current,
Geographic_Group_Current_ID,
Geographic_Group_Current_Name,
Geographic_Group_Proposed,
Geographic_Group_Proposed_ID,
Geographic_Group_Proposed_Name,
Profit_Center_Current,
Profit_Center_Current_ID,
Profit_Center_Current_Name,
Profit_Center_Proposed,
Profit_Center_Proposed_ID,
Profit_Center_Proposed_Name,
Sony_Payroll_Company_Current,
Sony_Payroll_Company_Current_ID,
Sony_Payroll_Company_Current_Name,
Sony_Payroll_Company_Proposed,
Sony_Payroll_Company_Proposed_ID,
Sony_Payroll_Company_Proposed_Name,
Time_Type_Current,
Time_Type_Current_ID,
Time_Type_Proposed,
Time_Type_Proposed_ID,
Pay_Rate_Type_Current,
Pay_Rate_Type_Current_ID,
Pay_Rate_Type_Proposed,
Pay_Rate_Type_Proposed_ID,
Paid_FTE_Current,
Paid_FTE_Proposed,
Job_Exempt_Current,
Job_Exempt_Proposed,
Base_Pay_Current,
Currency_8,
Base_Pay_Proposed,
Currency_9,
Hourly_Rate_Current_Amount,
Currency_6,
Hourly_Rate_Proposed_Amount,
Currency_7,
Business_Unit,
Division,
Sub_Division,
Department,
Sub_Department,
Line_of_Business,
Benefit_Code,
Organization_Level_Code,
Management_Level,
Hire_Date,
Original_Hire_Date,
Continuous_Service_Date,
Job_Code,
Job_Title,
Job_Family,
Job_Family_Group,
Business_Title,
Exempt_Status,
FTE,
Time_Type,
Pay_Rate_Type,
Frequency,
Compensation_Grade,
Hourly_Amount,
Currency,
Currency_1,
Base_Pay_Range_Segment,
ASPIRE_Target_Percentage,
ASPIRE_Bonus_Plan,
ASPIRE_Bonus_Amount,
Currency_2,
ASPIRE_Bonus_Amount_US,
Currency_3,
Last_Increase_Date,
Last_Increase_Amount,
Currency_4,
Last_Increase_Percent,
Last_Bonus_Date,
LTIP_Bonus_Amount,
Currency_5,
End_Employment_Date,
Employee_Type,
Contingent_Worker_Type,
SPE_Union_Code,
Union_Local_Name_Long_Name,
Work_Location,
Work_Address_City,
Work_Address_State,
Work_Address_Postal_Code,
Work_Address_Country,
Region,
Cost_Center,
SAP_Company,
Pay_Company,
Gender,
Age,
Hispanic_or_Latino,
Race,
Veteran_Status,
Disability,
Termination_Date,
Primary_Business_Partner,
Employee_Work_Email,
On_Leave,
Active_Status,
Manager,
Manager_Job_Title,
Manager_Work_Email,
Manager_Direct_Reports_Count,
Manager_Span_of_Control,
Source_FileName
)
SELECT 
$1,
$2,
$3,
$4,
$5,
$6,
$7,
$8,
$9,
$10,
$11,
$12,
$13,
$14,
$15,
$16,
$17,
$18,
$19,
$20,
$21,
$22,
$23,
$24,
$25,
$26,
$27,
$28,
$29,
$30,
$31,
$32,
$33,
$34,
$35,
$36,
$37,
$38,
$39,
$40,
$41,
$42,
$43,
$44,
$45,
$46,
$47,
$48,
$49,
$50,
$51,
$52,
$53,
$54,
$55,
$56,
$57,
$58,
$59,
$60,
$61,
$62,
$63,
$64,
$65,
$66,
$67,
$68,
$69,
$70,
$71,
$72,
$73,
$74,
$75,
$76,
$77,
$78,
$79,
$80,
$81,
$82,
$83,
$84,
$85,
$86,
$87,
$88,
$89,
$90,
$91,
$92,
$93,
$94,
$95,
$96,
$97,
$98,
$99,
$100,
$101,
$102,
$103,
$104,
$105,
$106,
$107,
$108,
$109,
$110,
$111,
$112,
$113,
$114,
$115,
$116,
$117,
$118,
$119,
$120,
$121,
$122,
$123,
$124,
$125,
$126,
$127,
$128,
$129,
$130,
$131,
$132,
$133,
$134,
$135,
$136,
$137,
$138,
$139,
$140,
$141,
$142,
$143,
$144,
$145,
$146,
$147,
$148,
$149,
$150,
$151,
$152,
$153,
$154,
$155,
$156,
$157,
$158,
$159,
$160,
$161,
$162,
$163,
$164,
$165,
$166,
$167,
$168,
$169,
$170,
$171,
$172,
$173
--METADATA$FILENAME
from @worker_load_instg/Worker_Snapshot_2010.csv (file_format => 'csv_load_format' ) t;


CREATE VIEW "PO_HRIS_DB"."Worker".po_wd_worker_vw as 

Select 
Workday_ID,
PreHire_ID,
PreHire_WID,
--Action_Event,
Transaction_Status,
Initiated_Date,
Initiating_Worker_ID,
Effective_Date,
Busniess_Process_Type,
Business_Process_Reason_Category,
Business_Process_Reason,
Business_Unit,
Division,
Sub_Division,
Department,
Sub_Department,
Line_of_Business,
Benefit_Code,
Organization_Level_Code,
Management_Level,
Hire_Date,
Original_Hire_Date,
Continuous_Service_Date,
hash(Job_Code) as Job_Code,
Job_Title,
Job_Family,
Job_Family_Group,
Business_Title,
Exempt_Status,
FTE,
Time_Type,
Pay_Rate_Type,
Frequency,
Compensation_Grade,
Hourly_Amount,
Currency,
Currency_1,
Base_Pay_Range_Segment,
ASPIRE_Target_Percentage,
ASPIRE_Bonus_Plan,
ASPIRE_Bonus_Amount,
Currency_2,
ASPIRE_Bonus_Amount_US,
Currency_3,
Last_Increase_Date,
Last_Increase_Amount,
Currency_4,
Last_Increase_Percent,
Last_Bonus_Date,
LTIP_Bonus_Amount,
Currency_5,
End_Employment_Date,
Employee_Type,
Contingent_Worker_Type,
SPE_Union_Code,
Union_Local_Name_Long_Name,
Work_Location,
Work_Address_City,
Work_Address_State,
Work_Address_Postal_Code,
Work_Address_Country,
Region,
Cost_Center,
SAP_Company,
Pay_Company,
Gender,
Age,
Hispanic_or_Latino,
Race,
Veteran_Status,
hash(Supervisory_Organization_Proposed_Name) as Supervisory,
Disability,
Termination_Date,
Primary_Business_Partner,
hash(Employee_Work_Email) as Employee_Work_Email,
On_Leave,
Active_Status,
Manager,
Manager_Job_Title,
hash(Manager_Work_Email) as Manager_Work_Email,
Manager_Direct_Reports_Count,
Manager_Span_of_Control
FROM "PO_STAGE_DB"."Worker".PO_WD_Worker_Stage;

--select * from "PO_HRIS_DB"."Worker".po_wd_worker_vw
   grant all privileges on database  PO_HRIS_DB to user "SSUMITHA";